// Oman Regions. Each map area is one of the 63 wilayats (data.js, from
// OpenStreetMap admin_level 6); the 11 governorates (muhafazat) are groups of them. Both levels can be asked by
// English name or in Arabic script (the form on bilingual signs, without the محافظة / ولاية prefix).

const LAYERS = {
  key: "omregions",
  size: [1000,1344],
  pad: 16,
  maxZoom: 40,
  labelScale: 0.24,
  fly: {"pad":1.6,"min":0.0375},
  street: {"bounds":[[16.6,51.9],[26.5,59.9]],"maxBounds":[[10,44],[32,66]]},
  hintLabel: "Color by governorate",
  exploreKind: "wilayats",
  kinds: [
    {
      key: "govs",
      label: "Governorates",
      noun: ["governorate","governorates"],
      prompt: "name",
      lang: "English",
      groups: [["North coast","",["MU","BS","BJ","MA"]],["Interior","",["BU","ZA","DA","SS","SJ"]],["South","",["WU","ZU"]]],
      areas: {"x":{"MU":["bukha","dibba","khasab","madha"],"BS":["khaburah","suwaiq","liwa","saham","shinas","sohar"],"BJ":["awabi","musanaah","barka","nakhal","rustaq","maawil"],"MA":["amerat","bawshar","muscat","muttrah","qurayyat","seeb"],"BU":["buraimi","sunaynah","mahdah"],"ZA":["dhank","ibri","yanqul"],"DA":["adam","hamra","akhdar","bahla","bidbid","izki","manah","nizwa","samail"],"SS":["mudhaibi","qabil","bidiyah","dima","ibra","sinaw","wbk"],"SJ":["kamil","jbba","jbbh","masirah","sur"],"WU":["jazir","duqm","haima","mahout"],"ZU":["mazyunah","dhalkut","mirbat","muqshin","rakhyut","sadah","salalah","shalim","taqah","thumrait"]}},
      name: {"x":{"MU":"Musandam","BS":"Al Batinah North","BJ":"Al Batinah South","MA":"Muscat","BU":"Al Buraimi","ZA":"Ad Dhahirah","DA":"Ad Dakhiliyah","SS":"Ash Sharqiyah North","SJ":"Ash Sharqiyah South","WU":"Al Wusta","ZU":"Dhofar"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"MU":"مسندم","BS":"شمال الباطنة","BJ":"جنوب الباطنة","MA":"مسقط","BU":"البريمي","ZA":"الظاهرة","DA":"الداخلية","SS":"شمال الشرقية","SJ":"جنوب الشرقية","WU":"الوسطى","ZU":"ظفار"}},
      about: {"x":{"MU":["Seat: Khasab","4 wilayats"],"BS":["Seat: Sohar","6 wilayats"],"BJ":["Seat: Rustaq","6 wilayats"],"MA":["Seat: Muscat","6 wilayats"],"BU":["Seat: Al Buraimi","3 wilayats"],"ZA":["Seat: Ibri","3 wilayats"],"DA":["Seat: Nizwa","9 wilayats"],"SS":["Seat: Ibra","7 wilayats"],"SJ":["Seat: Sur","5 wilayats"],"WU":["Seat: Haima","4 wilayats"],"ZU":["Seat: Salalah","10 wilayats"]}},
      clicked: "{name}",
    },
    {
      key: "govsAr",
      label: "Governorates in Arabic",
      noun: ["governorate","governorates"],
      prompt: "text",
      of: "govs",
      lang: "Arabic",
      groups: [["North coast","",["MU","BS","BJ","MA"]],["Interior","",["BU","ZA","DA","SS","SJ"]],["South","",["WU","ZU"]]],
      areas: {"x":{"MU":["bukha","dibba","khasab","madha"],"BS":["khaburah","suwaiq","liwa","saham","shinas","sohar"],"BJ":["awabi","musanaah","barka","nakhal","rustaq","maawil"],"MA":["amerat","bawshar","muscat","muttrah","qurayyat","seeb"],"BU":["buraimi","sunaynah","mahdah"],"ZA":["dhank","ibri","yanqul"],"DA":["adam","hamra","akhdar","bahla","bidbid","izki","manah","nizwa","samail"],"SS":["mudhaibi","qabil","bidiyah","dima","ibra","sinaw","wbk"],"SJ":["kamil","jbba","jbbh","masirah","sur"],"WU":["jazir","duqm","haima","mahout"],"ZU":["mazyunah","dhalkut","mirbat","muqshin","rakhyut","sadah","salalah","shalim","taqah","thumrait"]}},
      name: {"x":{"MU":"مسندم · Musandam","BS":"شمال الباطنة · Al Batinah North","BJ":"جنوب الباطنة · Al Batinah South","MA":"مسقط · Muscat","BU":"البريمي · Al Buraimi","ZA":"الظاهرة · Ad Dhahirah","DA":"الداخلية · Ad Dakhiliyah","SS":"شمال الشرقية · Ash Sharqiyah North","SJ":"جنوب الشرقية · Ash Sharqiyah South","WU":"الوسطى · Al Wusta","ZU":"ظفار · Dhofar"}},
      short: {"x":{"MU":"مسندم","BS":"شمال الباطنة","BJ":"جنوب الباطنة","MA":"مسقط","BU":"البريمي","ZA":"الظاهرة","DA":"الداخلية","SS":"شمال الشرقية","SJ":"جنوب الشرقية","WU":"الوسطى","ZU":"ظفار"}},
      chip: "{short}",
      chipTitle: {"x":{"MU":"Musandam","BS":"Al Batinah North","BJ":"Al Batinah South","MA":"Muscat","BU":"Al Buraimi","ZA":"Ad Dhahirah","DA":"Ad Dakhiliyah","SS":"Ash Sharqiyah North","SJ":"Ash Sharqiyah South","WU":"Al Wusta","ZU":"Dhofar"}},
      about: {"x":{"MU":["Seat: Khasab","4 wilayats"],"BS":["Seat: Sohar","6 wilayats"],"BJ":["Seat: Rustaq","6 wilayats"],"MA":["Seat: Muscat","6 wilayats"],"BU":["Seat: Al Buraimi","3 wilayats"],"ZA":["Seat: Ibri","3 wilayats"],"DA":["Seat: Nizwa","9 wilayats"],"SS":["Seat: Ibra","7 wilayats"],"SJ":["Seat: Sur","5 wilayats"],"WU":["Seat: Haima","4 wilayats"],"ZU":["Seat: Salalah","10 wilayats"]}},
      text: {"t":{"text":"{chip}","lang":"ar","cls":"city"}},
      clicked: "{name}",
    },
    {
      key: "wilayats",
      label: "Wilayats",
      noun: ["wilayat","wilayats"],
      prompt: "name",
      lang: "English",
      groups: [["Musandam","مسندم",["bukha","dibba","khasab","madha"]],["Al Buraimi","البريمي",["buraimi","sunaynah","mahdah"]],["Al Batinah North","شمال الباطنة",["khaburah","suwaiq","liwa","saham","shinas","sohar"]],["Al Batinah South","جنوب الباطنة",["awabi","musanaah","barka","nakhal","rustaq","maawil"]],["Muscat","مسقط",["amerat","bawshar","muscat","muttrah","qurayyat","seeb"]],["Ad Dhahirah","الظاهرة",["dhank","ibri","yanqul"]],["Ad Dakhiliyah","الداخلية",["adam","hamra","akhdar","bahla","bidbid","izki","manah","nizwa","samail"]],["Ash Sharqiyah North","شمال الشرقية",["mudhaibi","qabil","bidiyah","dima","ibra","sinaw","wbk"]],["Ash Sharqiyah South","جنوب الشرقية",["kamil","jbba","jbbh","masirah","sur"]],["Al Wusta","الوسطى",["jazir","duqm","haima","mahout"]],["Dhofar","ظفار",["mazyunah","dhalkut","mirbat","muqshin","rakhyut","sadah","salalah","shalim","taqah","thumrait"]]],
      areas: "@id",
      name: "{@en}",
      short: "{@en}",
      chip: "{@en}",
      chipTitle: "{@ar} · {group}",
      about: {"t":["{group} governorate"]},
      clicked: "{@en}",
    },
    {
      key: "wilayatsAr",
      label: "Wilayats in Arabic",
      noun: ["wilayat","wilayats"],
      prompt: "text",
      of: "wilayats",
      lang: "Arabic",
      groups: [["Musandam","مسندم",["bukha","dibba","khasab","madha"]],["Al Buraimi","البريمي",["buraimi","sunaynah","mahdah"]],["Al Batinah North","شمال الباطنة",["khaburah","suwaiq","liwa","saham","shinas","sohar"]],["Al Batinah South","جنوب الباطنة",["awabi","musanaah","barka","nakhal","rustaq","maawil"]],["Muscat","مسقط",["amerat","bawshar","muscat","muttrah","qurayyat","seeb"]],["Ad Dhahirah","الظاهرة",["dhank","ibri","yanqul"]],["Ad Dakhiliyah","الداخلية",["adam","hamra","akhdar","bahla","bidbid","izki","manah","nizwa","samail"]],["Ash Sharqiyah North","شمال الشرقية",["mudhaibi","qabil","bidiyah","dima","ibra","sinaw","wbk"]],["Ash Sharqiyah South","جنوب الشرقية",["kamil","jbba","jbbh","masirah","sur"]],["Al Wusta","الوسطى",["jazir","duqm","haima","mahout"]],["Dhofar","ظفار",["mazyunah","dhalkut","mirbat","muqshin","rakhyut","sadah","salalah","shalim","taqah","thumrait"]]],
      areas: "@id",
      name: "{@ar} · {@en}",
      short: "{@ar}",
      chip: "{@ar}",
      chipTitle: "{@en} · {group}",
      about: {"t":["{group} governorate"]},
      text: {"t":{"text":"{@ar}","lang":"ar","cls":"city"}},
      clicked: "{name}",
    },
  ],
  g: "{@gov}",
  explore: {"t":{"code":"{@ar}","title":"{@en}","sub":["{wilayats.about0} · {govs.chipTitle}"]}},
};
