// Bolivia Departments. 9 departments (OCHA COD-AB admin1) in 3 zones by whole
// department: Altiplano (Zona Andina: La Paz, Oruro, Potosí), Valleys (Zona Subandina: Cochabamba, Chuquisaca, Tarija),
// Lowlands (Llanos Orientales: Santa Cruz, Beni, Pando), as listed by the Embassy of Bolivia in France. The physical
// regions don't follow department borders exactly (northern La Paz is lowland, the Chaco reaches Tarija and
// Chuquisaca). Each department's capital: Wikipedia, Departments of Bolivia.

const LAYERS = {
  key: "bodept",
  size: [1000,1135],
  pad: 16,
  maxZoom: 20,
  labelScale: 0.12,
  fly: {"pad":1.6,"min":0.075},
  street: {"bounds":[[-22.9,-69.7],[-9.6,-57.4]],"maxBounds":[[-30,-82],[-2,-45]]},
  hintLabel: "Color by zone",
  exploreKind: "departments",
  kinds: [
    {
      key: "zones",
      label: "Zones",
      noun: ["zone","zones"],
      prompt: "name",
      hints: false,
      groups: [["Zones","",["A","V","L"]]],
      areas: {"x":{"A":["BO02","BO04","BO05"],"V":["BO01","BO03","BO06"],"L":["BO08","BO09","BO07"]}},
      name: {"x":{"A":"Altiplano","V":"Valleys","L":"Lowlands"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"A":"Zona Andina","V":"Zona Subandina","L":"Llanos Orientales"}},
      about: {"x":{"A":["Zona Andina","La Paz, Oruro, Potosí"],"V":["Zona Subandina","Chuquisaca, Cochabamba, Tarija"],"L":["Llanos Orientales","Beni, Pando, Santa Cruz"]}},
      clicked: "{name} ({@name})",
    },
    {
      key: "departments",
      label: "Departments",
      noun: ["department","departments"],
      prompt: "name",
      lang: "Names",
      groups: [["Altiplano","Zona Andina",["BO02","BO04","BO05"]],["Valleys","Zona Subandina",["BO01","BO03","BO06"]],["Lowlands","Llanos Orientales",["BO08","BO09","BO07"]]],
      areas: "@id",
      name: "{@name}",
      short: "{name}",
      chip: "{name}",
      chipTitle: {"t":"{name}","x":{"BO01":"Sucre","BO08":"Trinidad","BO09":"Cobija","BO07":"Santa Cruz de la Sierra"}},
      detail: ["Show zone","{group}"],
      about: {"t":["{group}","Capital: {chipTitle}","Phone zone {@phone}"]},
      clicked: "{name}",
    },
    {
      key: "capitals",
      label: "Capitals",
      noun: ["capital","capitals"],
      prompt: "name",
      of: "departments",
      lang: "Capitals",
      groups: [["Altiplano","Zona Andina",["BO02","BO04","BO05"]],["Valleys","Zona Subandina",["BO03","BO01","BO06"]],["Lowlands","Llanos Orientales",["BO09","BO07","BO08"]]],
      areas: "@id",
      name: {"t":"{@name}","x":{"BO01":"Sucre","BO09":"Cobija","BO07":"Santa Cruz de la Sierra","BO08":"Trinidad"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: "{@name}",
      detail: ["Show zone","{group}"],
      about: {"t":["{@name}","{group}"]},
      clicked: "{name} ({@name})",
    },
  ],
  g: "{@zone}",
  explore: {"t":{"code":"{@phone}","title":"{@name}","sub":["{zones.name}","{departments.about1}","{departments.about2}"]}},
};
