// Portugal Regions. Map areas are the 308 municipalities (CAOP2025, DGT), so every
// level is a grouping of them: mainland / Azores / Madeira, then the 18 districts and 2 autonomous regions.
// Road modes: national and regional roads (EN/ER) numbered 101–398 run north to south within each class (1945 road
// plan); each class is split into five number bands, and each mainland municipality belongs to the band whose roads
// have the most kilometres in it (OSM road refs; municipalities without such roads take their neighbours' band).
// The bands and their areas are this quiz's own grouping (approximate). Azores and Madeira are drawn as insets.

const LAYERS = {
  key: "ptregions",
  size: [1000,840],
  pad: 16,
  maxZoom: 40,
  labelScale: 0.22,
  fly: {"pad":1.6,"min":0.0375},
  street: {"bounds":[[36.9,-9.6],[42.2,-6.1]],"maxBounds":[[28,-35],[46,0]]},
  hintLabel: "Color by district",
  exploreKind: "districts",
  kinds: [
    {
      key: "parts",
      label: "Mainland & islands",
      noun: ["part","parts"],
      prompt: "name",
      groups: [["Portugal","",["C","A","M"]]],
      areas: "@part",
      name: {"x":{"C":"Mainland","A":"Azores","M":"Madeira"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: "{name}",
      about: {"x":{"C":"18 districts","A":"Autonomous region","M":"Autonomous region"}},
      clicked: "{name}",
    },
    {
      key: "districts",
      label: "Districts",
      noun: ["district","districts"],
      prompt: "name",
      groups: [["North","",["Braga","Bragança","Porto","Viana do Castelo","Vila Real"]],["Centre","",["Aveiro","Castelo Branco","Coimbra","Guarda","Leiria","Viseu"]],["West & Tagus","",["Lisboa","Santarém"]],["Alentejo","",["Beja","Évora","Portalegre","Setúbal"]],["Algarve","",["Faro"]],["Autonomous regions","",["Açores","Madeira"]]],
      areas: "@dist",
      name: {"t":"{id}","x":{"Lisboa":"Lisbon","Açores":"Azores"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: "{group}",
      about: {"x":{"Braga":["District · North","14 municipalities"],"Bragança":["District · North","12 municipalities"],"Porto":["District · North","18 municipalities"],"Viana do Castelo":["District · North","10 municipalities"],"Vila Real":["District · North","14 municipalities"],"Aveiro":["District · Centre","19 municipalities"],"Castelo Branco":["District · Centre","11 municipalities"],"Coimbra":["District · Centre","17 municipalities"],"Guarda":["District · Centre","14 municipalities"],"Leiria":["District · Centre","16 municipalities"],"Viseu":["District · Centre","24 municipalities"],"Lisboa":["District · West & Tagus","16 municipalities"],"Santarém":["District · West & Tagus","21 municipalities"],"Beja":["District · Alentejo","14 municipalities"],"Évora":["District · Alentejo","14 municipalities"],"Portalegre":["District · Alentejo","15 municipalities"],"Setúbal":["District · Alentejo","13 municipalities"],"Faro":["District · Algarve","16 municipalities"],"Açores":["Autonomous region","19 municipalities"],"Madeira":["Autonomous region","11 municipalities"]}},
      clicked: "{name}",
    },
    {
      key: "n1",
      label: "Roads 1xx",
      noun: ["band","bands"],
      prompt: "name",
      groups: [["N 1xx","north → south",["101-108","109-112","113-119","120-123","124-125"]]],
      areas: "@n1",
      name: {"x":{"101-108":"N 101–108","109-112":"N 109–112","113-119":"N 113–119","120-123":"N 120–123","124-125":"N 124–125"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"101-108":"Bragança · Guarda · Vila Real","109-112":"Castelo Branco · Coimbra · Aveiro","113-119":"Évora · Santarém · Portalegre","120-123":"Beja · Setúbal · Faro","124-125":"Faro"}},
      about: "{chipTitle}",
      clicked: {"t":"{name} ({@name})","x":{"3101":"Calheta","3102":"Câmara de Lobos","3103":"Funchal","3104":"Machico","3105":"Ponta do Sol","3106":"Porto Moniz","3107":"Ribeira Brava","3108":"Santa Cruz","3109":"Santana","3110":"São Vicente","3201":"Porto Santo","4101":"Vila do Porto","4201":"Lagoa","4202":"Nordeste","4203":"Ponta Delgada","4204":"Povoação","4205":"Ribeira Grande","4206":"Vila Franca do Campo","4301":"Angra do Heroísmo","4302":"Praia da Vitória","4401":"Santa Cruz da Graciosa","4501":"Calheta de São Jorge","4502":"Velas","4601":"Lajes do Pico","4602":"Madalena","4603":"São Roque do Pico","4701":"Horta","4801":"Lajes das Flores","4802":"Santa Cruz das Flores","4901":"Corvo"}},
    },
    {
      key: "n2",
      label: "Roads 2xx",
      noun: ["band","bands"],
      prompt: "name",
      groups: [["N 2xx","north → south",["201-221","222-241","242-251","252-265","266-270"]]],
      areas: "@n2",
      name: {"x":{"201-221":"N 201–221","222-241":"N 222–241","242-251":"N 242–251","252-265":"N 252–265","266-270":"N 266–270"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"201-221":"Bragança · Vila Real · Braga","222-241":"Castelo Branco · Viseu · Guarda","242-251":"Santarém · Portalegre · Lisbon","252-265":"Beja · Évora · Setúbal","266-270":"Faro · Beja"}},
      about: "{chipTitle}",
      clicked: {"t":"{name} ({@name})","x":{"3101":"Calheta","3102":"Câmara de Lobos","3103":"Funchal","3104":"Machico","3105":"Ponta do Sol","3106":"Porto Moniz","3107":"Ribeira Brava","3108":"Santa Cruz","3109":"Santana","3110":"São Vicente","3201":"Porto Santo","4101":"Vila do Porto","4201":"Lagoa","4202":"Nordeste","4203":"Ponta Delgada","4204":"Povoação","4205":"Ribeira Grande","4206":"Vila Franca do Campo","4301":"Angra do Heroísmo","4302":"Praia da Vitória","4401":"Santa Cruz da Graciosa","4501":"Calheta de São Jorge","4502":"Velas","4601":"Lajes do Pico","4602":"Madalena","4603":"São Roque do Pico","4701":"Horta","4801":"Lajes das Flores","4802":"Santa Cruz das Flores","4901":"Corvo"}},
    },
    {
      key: "n3",
      label: "Roads 3xx",
      noun: ["band","bands"],
      prompt: "name",
      groups: [["N 3xx","north → south",["301-325","326-355","356-375","376-393","394-398"]]],
      areas: "@n3",
      name: {"x":{"301-325":"N 301–325","326-355":"N 326–355","356-375":"N 356–375","376-393":"N 376–393","394-398":"N 394–398"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"301-325":"Bragança · Vila Real · Braga","326-355":"Castelo Branco · Guarda · Coimbra","356-375":"Portalegre · Santarém · Lisbon","376-393":"Beja · Évora · Setúbal","394-398":"Faro"}},
      about: "{chipTitle}",
      clicked: {"t":"{name} ({@name})","x":{"3101":"Calheta","3102":"Câmara de Lobos","3103":"Funchal","3104":"Machico","3105":"Ponta do Sol","3106":"Porto Moniz","3107":"Ribeira Brava","3108":"Santa Cruz","3109":"Santana","3110":"São Vicente","3201":"Porto Santo","4101":"Vila do Porto","4201":"Lagoa","4202":"Nordeste","4203":"Ponta Delgada","4204":"Povoação","4205":"Ribeira Grande","4206":"Vila Franca do Campo","4301":"Angra do Heroísmo","4302":"Praia da Vitória","4401":"Santa Cruz da Graciosa","4501":"Calheta de São Jorge","4502":"Velas","4601":"Lajes do Pico","4602":"Madalena","4603":"São Roque do Pico","4701":"Horta","4801":"Lajes das Flores","4802":"Santa Cruz das Flores","4901":"Corvo"}},
    },
  ],
  g: "{@dist}",
  explore: {"t":{"code":"","title":"{@name}","sub":["{districts.name}","{n1.name} · {n2.name} · {n3.name}"]},"x":{"3101":{"code":"","title":"Calheta","sub":["Ilha da Madeira · Madeira"]},"3102":{"code":"","title":"Câmara de Lobos","sub":["Ilha da Madeira · Madeira"]},"3103":{"code":"","title":"Funchal","sub":["Ilha da Madeira · Madeira"]},"3104":{"code":"","title":"Machico","sub":["Ilha da Madeira · Madeira"]},"3105":{"code":"","title":"Ponta do Sol","sub":["Ilha da Madeira · Madeira"]},"3106":{"code":"","title":"Porto Moniz","sub":["Ilha da Madeira · Madeira"]},"3107":{"code":"","title":"Ribeira Brava","sub":["Ilha da Madeira · Madeira"]},"3108":{"code":"","title":"Santa Cruz","sub":["Ilha da Madeira · Madeira"]},"3109":{"code":"","title":"Santana","sub":["Ilha da Madeira · Madeira"]},"3110":{"code":"","title":"São Vicente","sub":["Ilha da Madeira · Madeira"]},"3201":{"code":"","title":"Porto Santo","sub":["Ilha de Porto Santo · Madeira"]},"4101":{"code":"","title":"Vila do Porto","sub":["Ilha de Santa Maria · Azores"]},"4201":{"code":"","title":"Lagoa","sub":["Ilha de São Miguel · Azores"]},"4202":{"code":"","title":"Nordeste","sub":["Ilha de São Miguel · Azores"]},"4203":{"code":"","title":"Ponta Delgada","sub":["Ilha de São Miguel · Azores"]},"4204":{"code":"","title":"Povoação","sub":["Ilha de São Miguel · Azores"]},"4205":{"code":"","title":"Ribeira Grande","sub":["Ilha de São Miguel · Azores"]},"4206":{"code":"","title":"Vila Franca do Campo","sub":["Ilha de São Miguel · Azores"]},"4301":{"code":"","title":"Angra do Heroísmo","sub":["Ilha Terceira · Azores"]},"4302":{"code":"","title":"Praia da Vitória","sub":["Ilha Terceira · Azores"]},"4401":{"code":"","title":"Santa Cruz da Graciosa","sub":["Ilha da Graciosa · Azores"]},"4501":{"code":"","title":"Calheta de São Jorge","sub":["Ilha de São Jorge · Azores"]},"4502":{"code":"","title":"Velas","sub":["Ilha de São Jorge · Azores"]},"4601":{"code":"","title":"Lajes do Pico","sub":["Ilha do Pico · Azores"]},"4602":{"code":"","title":"Madalena","sub":["Ilha do Pico · Azores"]},"4603":{"code":"","title":"São Roque do Pico","sub":["Ilha do Pico · Azores"]},"4701":{"code":"","title":"Horta","sub":["Ilha do Faial · Azores"]},"4801":{"code":"","title":"Lajes das Flores","sub":["Ilha das Flores · Azores"]},"4802":{"code":"","title":"Santa Cruz das Flores","sub":["Ilha das Flores · Azores"]},"4901":{"code":"","title":"Corvo","sub":["Ilha do Corvo · Azores"]}}},
};
