// Argentina's national routes (rutas nacionales) and the provinces each runs through, by ISO 3166-2 letter, longest
// section first. Measured from IGN's "Red vial nacional" layer inside IGN's province polygons: a province counts from
// 2 km of route (a shorter route: its longest section), plus RN 16 into Corrientes and RN 142 into San Juan,
// short bridge-end sections that es.wikipedia's route table also lists. wiki: true = not in the IGN layer, provinces
// from es.wikipedia. Variant codes (1V09, 24CA, V143…) are left out. Source: FUENTE: Instituto Geográfico Nacional de
// la República Argentina (Capas SIG, free use with credit).
const ROUTES = [
  { id: '1', p: ['B', 'C'] },
  { id: '3', p: ['B', 'Z', 'U', 'V', 'R'] },
  { id: '5', p: ['B', 'L'] },
  { id: '7', p: ['M', 'B', 'D', 'X', 'S'] },
  { id: '8', p: ['B', 'X', 'S', 'D'] },
  { id: '9', p: ['X', 'B', 'Y', 'S', 'A', 'G', 'T'] },
  { id: '11', p: ['S', 'P', 'H'] },
  { id: '12', p: ['W', 'E', 'N', 'B'] },
  { id: '14', p: ['E', 'W', 'N'] },
  { id: '16', p: ['H', 'A', 'G', 'W'] },
  { id: '18', p: ['E'] },
  { id: '19', p: ['X', 'S'] },
  { id: '20', p: ['D', 'J', 'X'] },
  { id: '22', p: ['R', 'Q', 'B', 'L'] },
  { id: '23', p: ['R'] },
  { id: '25', p: ['U'] },
  { id: '26', p: ['U'] },
  { id: '33', p: ['B', 'S'] },
  { id: '34', p: ['G', 'A', 'S', 'Y', 'T'] },
  { id: '35', p: ['L', 'X', 'B'] },
  { id: '36', p: ['X'] },
  { id: '38', p: ['F', 'X', 'T', 'K'] },
  { id: '40', p: ['Z', 'Q', 'M', 'U', 'J', 'Y', 'A', 'F', 'K', 'R', 'T'] },
  { id: '50', p: ['A'] },
  { id: '51', p: ['A', 'Y'] },
  { id: '52', p: ['Y', 'A'] },
  { id: '60', p: ['K', 'X', 'F'] },
  { id: '64', p: ['G', 'K', 'T'] },
  { id: '65', p: ['T'] },
  { id: '66', p: ['Y'] },
  { id: '68', p: ['A'] },
  { id: '73', p: ['F'] },
  { id: '74', p: ['F'] },
  { id: '75', p: ['F'] },
  { id: '76', p: ['F'] },
  { id: '77', p: ['F', 'X'] },
  { id: '78', p: ['F'] },
  { id: '79', p: ['F', 'D', 'K'] },
  { id: '81', p: ['P', 'A'] },
  { id: '86', p: ['P', 'A'] },
  { id: '89', p: ['G', 'H'] },
  { id: '95', p: ['H', 'S', 'P'] },
  { id: '98', p: ['S', 'G'] },
  { id: '101', p: ['N'] },
  { id: '105', p: ['N'] },
  { id: '117', p: ['W'] },
  { id: '118', p: ['W'] },
  { id: '119', p: ['W'] },
  { id: '120', p: ['W'] },
  { id: '121', p: ['W'] },
  { id: '122', p: ['W'] },
  { id: '123', p: ['W'] },
  { id: '127', p: ['E', 'W'] },
  { id: '130', p: ['E'] },
  { id: '131', p: ['E'] },
  { id: '135', p: ['E'] },
  { id: '136', p: ['E'] },
  { id: '141', p: ['J', 'F'] },
  { id: '142', p: ['M', 'J'] },
  { id: '143', p: ['M', 'L'] },
  { id: '144', p: ['M'] },
  { id: '145', p: ['M'] },
  { id: '146', p: ['D', 'M'] },
  { id: '147', p: ['D'] },
  { id: '148', p: ['X'] },
  { id: '149', p: ['J', 'M'] },
  { id: '150', p: ['J', 'F'] },
  { id: '151', p: ['L', 'R'] },
  { id: '152', p: ['L'] },
  { id: '153', p: ['J', 'M'] },
  { id: '154', p: ['L'] },
  { id: '157', p: ['T', 'K', 'G'] },
  { id: '158', p: ['X'] },
  { id: '168', p: ['S'] },
  { id: '173', p: ['S'] },
  { id: '174', p: ['E', 'S'] },
  { id: '175', p: ['S'] },
  { id: '177', p: ['S'], wiki: true },
  { id: '178', p: ['S', 'B'] },
  { id: '188', p: ['B', 'M', 'L', 'D'] },
  { id: '193', p: ['B'] },
  { id: '205', p: ['B'] },
  { id: '226', p: ['B'] },
  { id: '228', p: ['B'] },
  { id: '229', p: ['B'] },
  { id: '231', p: ['Q'] },
  { id: '232', p: ['L', 'R'] },
  { id: '234', p: ['Q'] },
  { id: '237', p: ['Q', 'R'] },
  { id: '242', p: ['Q'] },
  { id: '249', p: ['B'] },
  { id: '250', p: ['R'] },
  { id: '251', p: ['R'] },
  { id: '252', p: ['B'] },
  { id: '259', p: ['U'] },
  { id: '260', p: ['U'] },
  { id: '281', p: ['Z'] },
  { id: '288', p: ['Z'] },
  { id: '293', p: ['Z'] },
  { id: 'A001', p: ['B', 'C'] },
  { id: 'A002', p: ['B'] },
  { id: 'A003', p: ['B'] },
  { id: 'A004', p: ['B'] },
  { id: 'A005', p: ['X'] },
  { id: 'A006', p: ['M'], wiki: true },
  { id: 'A007', p: ['S'] },
  { id: 'A008', p: ['S'] },
  { id: 'A009', p: ['S'] },
  { id: 'A010', p: ['U'] },
  { id: 'A011', p: ['P'] },
  { id: 'A012', p: ['S'] },
  { id: 'A013', p: ['B'] },
  { id: 'A014', p: ['J'] },
  { id: 'A015', p: ['E'] },
  { id: 'A016', p: ['T'] },
  { id: 'A019', p: ['X'] },
  { id: 'A022', p: ['Q', 'R'] },
  { id: 'A025', p: ['R'] },
  { id: 'A026', p: ['R'] },
];
