// Bulgaria Provinces. Each map area is one of the 28 provinces (oblasti), with
// their NUTS-2 planning regions (Eurostat) and the three electricity distribution areas, which follow province lines:
// ERM Zapad (Electrohold group, CEZ until 2021) in 10 western provinces, Elektrorazpredelenie Yug (EVN) in 9 in the
// south-east and Elektrorazpredelenie Sever (Energo-Pro) in 9 in the north-east.

const LAYERS = {
  key: "bgregions",
  size: [1000,659],
  pad: 16,
  maxZoom: 30,
  labelScale: 0.25,
  fly: {"pad":1.6,"min":0.05},
  street: {"bounds":[[41.2,22.3],[44.25,28.65]],"maxBounds":[[38,17],[47,34]]},
  hintLabel: "Color by planning region",
  exploreKind: "provinces",
  kinds: [
    {
      key: "provinces",
      label: "Provinces",
      noun: ["province","provinces"],
      prompt: "name",
      lang: "English",
      groups: [["North-West","",["11","12","15","05","06"]],["North-Central","",["07","17","18","19","04"]],["North-East","",["08","27","25","03"]],["South-East","",["02","20","24","28"]],["South-West","",["01","10","14","22","23"]],["South-Central","",["26","09","13","16","21"]]],
      areas: "@id",
      name: {"t":"{@en}","x":{"22":"Sofia City","23":"Sofia Province"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"t":"{@bg}","x":{"23":"Софийска област"}},
      detail: ["Show capital area code",{"x":{"10":"078","11":"068","12":"096","13":"034","14":"076","15":"064","16":"032","17":"084","18":"082","19":"086","20":"044","21":"030","22":"02","23":"02","24":"042","25":"060","26":"038","27":"054","28":"046","05":"094","06":"092","07":"066","04":"062","08":"058","03":"052","02":"056","01":"073","09":"036"}}],
      about: {"x":{"10":["South-West · Electrohold (CEZ)","Area code 078"],"11":["North-West · Electrohold (CEZ)","Area code 068"],"12":["North-West · Electrohold (CEZ)","Area code 096"],"13":["South-Central · EVN","Area code 034"],"14":["South-West · Electrohold (CEZ)","Area code 076"],"15":["North-West · Electrohold (CEZ)","Area code 064"],"16":["South-Central · EVN","Area code 032"],"17":["North-Central · Energo-Pro","Area code 084"],"18":["North-Central · Energo-Pro","Area code 082"],"19":["North-Central · Energo-Pro","Area code 086"],"20":["South-East · EVN","Area code 044"],"21":["South-Central · EVN","Area code 030"],"22":["South-West · Electrohold (CEZ)","Area code 02"],"23":["South-West · Electrohold (CEZ)","Area code 02"],"24":["South-East · EVN","Area code 042"],"25":["North-East · Energo-Pro","Area code 060"],"26":["South-Central · EVN","Area code 038"],"27":["North-East · Energo-Pro","Area code 054"],"28":["South-East · EVN","Area code 046"],"05":["North-West · Electrohold (CEZ)","Area code 094"],"06":["North-West · Electrohold (CEZ)","Area code 092"],"07":["North-Central · Energo-Pro","Area code 066"],"04":["North-Central · Energo-Pro","Area code 062"],"08":["North-East · Energo-Pro","Area code 058"],"03":["North-East · Energo-Pro","Area code 052"],"02":["South-East · EVN","Area code 056"],"01":["South-West · Electrohold (CEZ)","Area code 073"],"09":["South-Central · EVN","Area code 036"]}},
      clicked: "{name}",
    },
    {
      key: "cyrillic",
      label: "Cyrillic",
      noun: ["province","provinces"],
      prompt: "text",
      of: "provinces",
      lang: "Bulgarian",
      groups: [["North-West","",["11","12","15","05","06"]],["North-Central","",["07","17","18","19","04"]],["North-East","",["08","27","25","03"]],["South-East","",["02","20","24","28"]],["South-West","",["01","10","14","22","23"]],["South-Central","",["26","09","13","16","21"]]],
      areas: "@id",
      name: {"t":"{@bg} · {@en}","x":{"22":"София-град · Sofia City","23":"Софийска област · Sofia Province"}},
      short: {"t":"{@bg}","x":{"23":"Софийска област"}},
      chip: "{short}",
      chipTitle: {"t":"{@en}","x":{"22":"Sofia City","23":"Sofia Province"}},
      about: {"x":{"10":["South-West · Electrohold (CEZ)","Area code 078"],"11":["North-West · Electrohold (CEZ)","Area code 068"],"12":["North-West · Electrohold (CEZ)","Area code 096"],"13":["South-Central · EVN","Area code 034"],"14":["South-West · Electrohold (CEZ)","Area code 076"],"15":["North-West · Electrohold (CEZ)","Area code 064"],"16":["South-Central · EVN","Area code 032"],"17":["North-Central · Energo-Pro","Area code 084"],"18":["North-Central · Energo-Pro","Area code 082"],"19":["North-Central · Energo-Pro","Area code 086"],"20":["South-East · EVN","Area code 044"],"21":["South-Central · EVN","Area code 030"],"22":["South-West · Electrohold (CEZ)","Area code 02"],"23":["South-West · Electrohold (CEZ)","Area code 02"],"24":["South-East · EVN","Area code 042"],"25":["North-East · Energo-Pro","Area code 060"],"26":["South-Central · EVN","Area code 038"],"27":["North-East · Energo-Pro","Area code 054"],"28":["South-East · EVN","Area code 046"],"05":["North-West · Electrohold (CEZ)","Area code 094"],"06":["North-West · Electrohold (CEZ)","Area code 092"],"07":["North-Central · Energo-Pro","Area code 066"],"04":["North-Central · Energo-Pro","Area code 062"],"08":["North-East · Energo-Pro","Area code 058"],"03":["North-East · Energo-Pro","Area code 052"],"02":["South-East · EVN","Area code 056"],"01":["South-West · Electrohold (CEZ)","Area code 073"],"09":["South-Central · EVN","Area code 036"]}},
      text: {"t":{"text":"{chip}","lang":"bg","cls":"city"}},
      clicked: "{name}",
    },
    {
      key: "nuts",
      label: "Planning regions",
      groupsOnly: true,
      noun: ["region","regions"],
      prompt: "name",
      hints: false,
      groups: [["Planning regions","NUTS 2",["BG31","BG32","BG33","BG34","BG41","BG42"]]],
      areas: {"x":{"BG31":["11","12","15","05","06"],"BG32":["07","17","18","19","04"],"BG33":["08","27","25","03"],"BG34":["02","20","24","28"],"BG41":["01","10","14","22","23"],"BG42":["26","09","13","16","21"]}},
      name: {"x":{"BG31":"North-West","BG32":"North-Central","BG33":"North-East","BG34":"South-East","BG41":"South-West","BG42":"South-Central"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"BG31":"Lovech, Montana, Pleven, Vidin, Vratsa","BG32":"Gabrovo, Razgrad, Ruse, Silistra, Veliko Tarnovo","BG33":"Dobrich, Shumen, Targovishte, Varna","BG34":"Burgas, Sliven, Stara Zagora, Yambol","BG41":"Blagoevgrad, Kyustendil, Pernik, Sofia City, Sofia Province","BG42":"Haskovo, Kardzhali, Pazardzhik, Plovdiv, Smolyan"}},
      about: {"t":["{chipTitle}"]},
      clicked: {"t":"{name} ({@en})","x":{"22":"South-West (Sofia City)","23":"South-West (Sofia Province)"}},
    },
    {
      key: "power",
      label: "Power companies",
      noun: ["company","companies"],
      prompt: "name",
      hints: false,
      groups: [["Distribution areas","",["W","S","N"]]],
      areas: "@power",
      name: {"x":{"W":"Electrohold (CEZ)","S":"EVN","N":"Energo-Pro"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"W":"ЕРМ Запад · Електрохолд","S":"Електроразпределение Юг · EVN","N":"Електроразпределение Север · Energo-Pro"}},
      about: {"x":{"W":["ЕРМ Запад · Електрохолд","Blagoevgrad, Kyustendil, Lovech, Montana, Pernik, Pleven, Sofia City, Sofia Province, Vidin, Vratsa"],"S":["Електроразпределение Юг · EVN","Burgas, Haskovo, Kardzhali, Pazardzhik, Plovdiv, Sliven, Smolyan, Stara Zagora, Yambol"],"N":["Електроразпределение Север · Energo-Pro","Dobrich, Gabrovo, Razgrad, Ruse, Shumen, Silistra, Targovishte, Varna, Veliko Tarnovo"]}},
      clicked: {"t":"{name} ({@en})","x":{"22":"Electrohold (CEZ) (Sofia City)","23":"Electrohold (CEZ) (Sofia Province)"}},
    },
  ],
  g: "{@nuts}",
  explore: {"t":{"code":"{cyrillic.chip}","title":"{provinces.name}","sub":["{nuts.name}","{power.about0}"]}},
};
