// Japan Regions. Each map area is a prefecture, or the part of one served by one
// power utility (Shizuoka, Gifu, Mie, Fukui, Hyogo, Kagawa and Ehime are split), built from e-Stat 2020 census small
// areas. Kinds: the 8 regions (chihō), the 47 prefectures by English name and in kanji, and the 10 power utilities
// whose plates are on the utility poles. Area fields: pf prefecture (JIS number), pw utility, rg region.

const LAYERS = {
  key: "jpregions",
  size: [1000,1134],
  pad: 16,
  maxZoom: 40,
  labelScale: 0.22,
  fly: {"pad":1.6,"min":0.0375},
  street: {"bounds":[[24,123],[45.6,146]],"maxBounds":[[18,115],[50,158]]},
  hintLabel: "Color by region",
  exploreKind: "prefectures",
  kinds: [
    {
      key: "regions",
      label: "Regions",
      noun: ["region","regions"],
      prompt: "name",
      hints: false,
      groups: [["Regions","",["HK","TH","KT","CB","KK","CG","SK","KY"]]],
      areas: "@rg",
      name: {"x":{"HK":"Hokkaido","TH":"Tohoku","KT":"Kanto","CB":"Chubu","KK":"Kinki","CG":"Chugoku","SK":"Shikoku","KY":"Kyushu & Okinawa"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"HK":"北海道","TH":"東北","KT":"関東","CB":"中部","KK":"近畿","CG":"中国","SK":"四国","KY":"九州・沖縄"}},
      about: {"x":{"HK":["北海道","Hokkaido"],"TH":["東北","Aomori, Iwate, Miyagi, Akita, Yamagata, Fukushima"],"KT":["関東","Ibaraki, Tochigi, Gunma, Saitama, Chiba, Tokyo, Kanagawa"],"CB":["中部","Niigata, Toyama, Ishikawa, Fukui, Yamanashi, Nagano, Gifu, Shizuoka, Aichi"],"KK":["近畿","Mie, Shiga, Kyoto, Osaka, Hyogo, Nara, Wakayama"],"CG":["中国","Tottori, Shimane, Okayama, Hiroshima, Yamaguchi"],"SK":["四国","Tokushima, Kagawa, Ehime, Kochi"],"KY":["九州・沖縄","Fukuoka, Saga, Nagasaki, Kumamoto, Oita, Miyazaki, Kagoshima, Okinawa"]}},
      clicked: {"x":{"01-hokkaido":"Hokkaido (Hokkaido)","02-tohoku":"Tohoku (Aomori)","03-tohoku":"Tohoku (Iwate)","04-tohoku":"Tohoku (Miyagi)","05-tohoku":"Tohoku (Akita)","06-tohoku":"Tohoku (Yamagata)","07-tohoku":"Tohoku (Fukushima)","08-tepco":"Kanto (Ibaraki)","09-tepco":"Kanto (Tochigi)","10-tepco":"Kanto (Gunma)","11-tepco":"Kanto (Saitama)","12-tepco":"Kanto (Chiba)","13-tepco":"Kanto (Tokyo)","14-tepco":"Kanto (Kanagawa)","15-tohoku":"Chubu (Niigata)","16-hokuriku":"Chubu (Toyama)","17-hokuriku":"Chubu (Ishikawa)","18-kansai":"Chubu (Fukui)","18-hokuriku":"Chubu (Fukui)","19-tepco":"Chubu (Yamanashi)","20-chubu":"Chubu (Nagano)","21-chubu":"Chubu (Gifu)","21-hokuriku":"Chubu (Gifu)","21-kansai":"Chubu (Gifu)","22-tepco":"Chubu (Shizuoka)","22-chubu":"Chubu (Shizuoka)","23-chubu":"Chubu (Aichi)","24-chubu":"Kinki (Mie)","24-kansai":"Kinki (Mie)","25-kansai":"Kinki (Shiga)","26-kansai":"Kinki (Kyoto)","27-kansai":"Kinki (Osaka)","28-kansai":"Kinki (Hyogo)","28-chugoku":"Kinki (Hyogo)","29-kansai":"Kinki (Nara)","30-kansai":"Kinki (Wakayama)","31-chugoku":"Chugoku (Tottori)","32-chugoku":"Chugoku (Shimane)","33-chugoku":"Chugoku (Okayama)","34-chugoku":"Chugoku (Hiroshima)","35-chugoku":"Chugoku (Yamaguchi)","36-shikoku":"Shikoku (Tokushima)","37-shikoku":"Shikoku (Kagawa)","37-chugoku":"Shikoku (Kagawa)","38-shikoku":"Shikoku (Ehime)","38-chugoku":"Shikoku (Ehime)","39-shikoku":"Shikoku (Kochi)","40-kyushu":"Kyushu & Okinawa (Fukuoka)","41-kyushu":"Kyushu & Okinawa (Saga)","42-kyushu":"Kyushu & Okinawa (Nagasaki)","43-kyushu":"Kyushu & Okinawa (Kumamoto)","44-kyushu":"Kyushu & Okinawa (Oita)","45-kyushu":"Kyushu & Okinawa (Miyazaki)","46-kyushu":"Kyushu & Okinawa (Kagoshima)","47-okinawa":"Kyushu & Okinawa (Okinawa)"}},
    },
    {
      key: "prefectures",
      label: "Prefectures",
      noun: ["prefecture","prefectures"],
      prompt: "name",
      lang: "English",
      groups: [["Hokkaido","",["p01"]],["Tohoku","",["p05","p02","p07","p03","p04","p06"]],["Kanto","",["p12","p10","p08","p14","p11","p09","p13"]],["Chubu","",["p23","p18","p21","p17","p20","p15","p22","p16","p19"]],["Kinki","",["p28","p26","p24","p29","p27","p25","p30"]],["Chugoku","",["p34","p33","p32","p31","p35"]],["Shikoku","",["p38","p37","p39","p36"]],["Kyushu & Okinawa","",["p40","p46","p43","p45","p42","p44","p47","p41"]]],
      areas: {"x":{"p01":["01-hokkaido"],"p05":["05-tohoku"],"p02":["02-tohoku"],"p07":["07-tohoku"],"p03":["03-tohoku"],"p04":["04-tohoku"],"p06":["06-tohoku"],"p12":["12-tepco"],"p10":["10-tepco"],"p08":["08-tepco"],"p14":["14-tepco"],"p11":["11-tepco"],"p09":["09-tepco"],"p13":["13-tepco"],"p23":["23-chubu"],"p18":["18-kansai","18-hokuriku"],"p21":["21-chubu","21-hokuriku","21-kansai"],"p17":["17-hokuriku"],"p20":["20-chubu"],"p15":["15-tohoku"],"p22":["22-tepco","22-chubu"],"p16":["16-hokuriku"],"p19":["19-tepco"],"p28":["28-kansai","28-chugoku"],"p26":["26-kansai"],"p24":["24-chubu","24-kansai"],"p29":["29-kansai"],"p27":["27-kansai"],"p25":["25-kansai"],"p30":["30-kansai"],"p34":["34-chugoku"],"p33":["33-chugoku"],"p32":["32-chugoku"],"p31":["31-chugoku"],"p35":["35-chugoku"],"p38":["38-shikoku","38-chugoku"],"p37":["37-shikoku","37-chugoku"],"p39":["39-shikoku"],"p36":["36-shikoku"],"p40":["40-kyushu"],"p46":["46-kyushu"],"p43":["43-kyushu"],"p45":["45-kyushu"],"p42":["42-kyushu"],"p44":["44-kyushu"],"p47":["47-okinawa"],"p41":["41-kyushu"]}},
      name: {"x":{"p01":"Hokkaido","p05":"Akita","p02":"Aomori","p07":"Fukushima","p03":"Iwate","p04":"Miyagi","p06":"Yamagata","p12":"Chiba","p10":"Gunma","p08":"Ibaraki","p14":"Kanagawa","p11":"Saitama","p09":"Tochigi","p13":"Tokyo","p23":"Aichi","p18":"Fukui","p21":"Gifu","p17":"Ishikawa","p20":"Nagano","p15":"Niigata","p22":"Shizuoka","p16":"Toyama","p19":"Yamanashi","p28":"Hyogo","p26":"Kyoto","p24":"Mie","p29":"Nara","p27":"Osaka","p25":"Shiga","p30":"Wakayama","p34":"Hiroshima","p33":"Okayama","p32":"Shimane","p31":"Tottori","p35":"Yamaguchi","p38":"Ehime","p37":"Kagawa","p39":"Kochi","p36":"Tokushima","p40":"Fukuoka","p46":"Kagoshima","p43":"Kumamoto","p45":"Miyazaki","p42":"Nagasaki","p44":"Oita","p47":"Okinawa","p41":"Saga"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"p01":"北海道","p05":"秋田県","p02":"青森県","p07":"福島県","p03":"岩手県","p04":"宮城県","p06":"山形県","p12":"千葉県","p10":"群馬県","p08":"茨城県","p14":"神奈川県","p11":"埼玉県","p09":"栃木県","p13":"東京都","p23":"愛知県","p18":"福井県","p21":"岐阜県","p17":"石川県","p20":"長野県","p15":"新潟県","p22":"静岡県","p16":"富山県","p19":"山梨県","p28":"兵庫県","p26":"京都府","p24":"三重県","p29":"奈良県","p27":"大阪府","p25":"滋賀県","p30":"和歌山県","p34":"広島県","p33":"岡山県","p32":"島根県","p31":"鳥取県","p35":"山口県","p38":"愛媛県","p37":"香川県","p39":"高知県","p36":"徳島県","p40":"福岡県","p46":"鹿児島県","p43":"熊本県","p45":"宮崎県","p42":"長崎県","p44":"大分県","p47":"沖縄県","p41":"佐賀県"}},
      about: {"t":["{chipTitle}","{group} region"]},
      clicked: "{name}",
    },
    {
      key: "kanji",
      label: "Kanji",
      noun: ["prefecture","prefectures"],
      prompt: "text",
      of: "prefectures",
      lang: "Japanese",
      groups: [["Hokkaido","",["p01"]],["Tohoku","",["p05","p02","p07","p03","p04","p06"]],["Kanto","",["p12","p10","p08","p14","p11","p09","p13"]],["Chubu","",["p23","p18","p21","p17","p20","p15","p22","p16","p19"]],["Kinki","",["p28","p26","p24","p29","p27","p25","p30"]],["Chugoku","",["p34","p33","p32","p31","p35"]],["Shikoku","",["p38","p37","p39","p36"]],["Kyushu & Okinawa","",["p40","p46","p43","p45","p42","p44","p47","p41"]]],
      areas: {"x":{"p01":["01-hokkaido"],"p05":["05-tohoku"],"p02":["02-tohoku"],"p07":["07-tohoku"],"p03":["03-tohoku"],"p04":["04-tohoku"],"p06":["06-tohoku"],"p12":["12-tepco"],"p10":["10-tepco"],"p08":["08-tepco"],"p14":["14-tepco"],"p11":["11-tepco"],"p09":["09-tepco"],"p13":["13-tepco"],"p23":["23-chubu"],"p18":["18-kansai","18-hokuriku"],"p21":["21-chubu","21-hokuriku","21-kansai"],"p17":["17-hokuriku"],"p20":["20-chubu"],"p15":["15-tohoku"],"p22":["22-tepco","22-chubu"],"p16":["16-hokuriku"],"p19":["19-tepco"],"p28":["28-kansai","28-chugoku"],"p26":["26-kansai"],"p24":["24-chubu","24-kansai"],"p29":["29-kansai"],"p27":["27-kansai"],"p25":["25-kansai"],"p30":["30-kansai"],"p34":["34-chugoku"],"p33":["33-chugoku"],"p32":["32-chugoku"],"p31":["31-chugoku"],"p35":["35-chugoku"],"p38":["38-shikoku","38-chugoku"],"p37":["37-shikoku","37-chugoku"],"p39":["39-shikoku"],"p36":["36-shikoku"],"p40":["40-kyushu"],"p46":["46-kyushu"],"p43":["43-kyushu"],"p45":["45-kyushu"],"p42":["42-kyushu"],"p44":["44-kyushu"],"p47":["47-okinawa"],"p41":["41-kyushu"]}},
      name: {"x":{"p01":"北海道","p05":"秋田県","p02":"青森県","p07":"福島県","p03":"岩手県","p04":"宮城県","p06":"山形県","p12":"千葉県","p10":"群馬県","p08":"茨城県","p14":"神奈川県","p11":"埼玉県","p09":"栃木県","p13":"東京都","p23":"愛知県","p18":"福井県","p21":"岐阜県","p17":"石川県","p20":"長野県","p15":"新潟県","p22":"静岡県","p16":"富山県","p19":"山梨県","p28":"兵庫県","p26":"京都府","p24":"三重県","p29":"奈良県","p27":"大阪府","p25":"滋賀県","p30":"和歌山県","p34":"広島県","p33":"岡山県","p32":"島根県","p31":"鳥取県","p35":"山口県","p38":"愛媛県","p37":"香川県","p39":"高知県","p36":"徳島県","p40":"福岡県","p46":"鹿児島県","p43":"熊本県","p45":"宮崎県","p42":"長崎県","p44":"大分県","p47":"沖縄県","p41":"佐賀県"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"p01":"Hokkaido","p05":"Akita","p02":"Aomori","p07":"Fukushima","p03":"Iwate","p04":"Miyagi","p06":"Yamagata","p12":"Chiba","p10":"Gunma","p08":"Ibaraki","p14":"Kanagawa","p11":"Saitama","p09":"Tochigi","p13":"Tokyo","p23":"Aichi","p18":"Fukui","p21":"Gifu","p17":"Ishikawa","p20":"Nagano","p15":"Niigata","p22":"Shizuoka","p16":"Toyama","p19":"Yamanashi","p28":"Hyogo","p26":"Kyoto","p24":"Mie","p29":"Nara","p27":"Osaka","p25":"Shiga","p30":"Wakayama","p34":"Hiroshima","p33":"Okayama","p32":"Shimane","p31":"Tottori","p35":"Yamaguchi","p38":"Ehime","p37":"Kagawa","p39":"Kochi","p36":"Tokushima","p40":"Fukuoka","p46":"Kagoshima","p43":"Kumamoto","p45":"Miyazaki","p42":"Nagasaki","p44":"Oita","p47":"Okinawa","p41":"Saga"}},
      about: {"t":["{chipTitle}","{group} region"]},
      text: {"t":{"text":"{name}","lang":"ja","cls":"city"}},
      clicked: "{name} · {chipTitle}",
    },
    {
      key: "power",
      label: "Power companies",
      noun: ["company","companies"],
      prompt: "name",
      hints: false,
      groups: [["Utilities","",["hokkaido","tohoku","tepco","chubu","hokuriku","kansai","chugoku","shikoku","kyushu","okinawa"]]],
      areas: "@pw",
      name: {"x":{"hokkaido":"Hokkaido Electric","tohoku":"Tohoku Electric","tepco":"TEPCO","chubu":"Chubu Electric","hokuriku":"Hokuriku Electric","kansai":"Kansai Electric","chugoku":"Chugoku Electric","shikoku":"Shikoku Electric","kyushu":"Kyushu Electric","okinawa":"Okinawa Electric"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"hokkaido":"北海道電力","tohoku":"東北電力","tepco":"東京電力","chubu":"中部電力","hokuriku":"北陸電力","kansai":"関西電力","chugoku":"中国電力","shikoku":"四国電力","kyushu":"九州電力","okinawa":"沖縄電力"}},
      about: {"x":{"hokkaido":["北海道電力","Hokkaido"],"tohoku":["東北電力","Aomori, Iwate, Miyagi, Akita, Yamagata, Fukushima, Niigata"],"tepco":["東京電力","Ibaraki, Tochigi, Gunma, Saitama, Chiba, Tokyo, Kanagawa, Yamanashi, Shizuoka (part)"],"chubu":["中部電力","Nagano, Gifu (part), Shizuoka (part), Aichi, Mie (part)"],"hokuriku":["北陸電力","Toyama, Ishikawa, Fukui (part), Gifu (part)"],"kansai":["関西電力","Fukui (part), Gifu (part), Mie (part), Shiga, Kyoto, Osaka, Hyogo (part), Nara, Wakayama"],"chugoku":["中国電力","Hyogo (part), Tottori, Shimane, Okayama, Hiroshima, Yamaguchi, Kagawa (part), Ehime (part)"],"shikoku":["四国電力","Tokushima, Kagawa (part), Ehime (part), Kochi"],"kyushu":["九州電力","Fukuoka, Saga, Nagasaki, Kumamoto, Oita, Miyazaki, Kagoshima"],"okinawa":["沖縄電力","Okinawa"]}},
      clicked: {"x":{"01-hokkaido":"Hokkaido Electric (Hokkaido)","02-tohoku":"Tohoku Electric (Aomori)","03-tohoku":"Tohoku Electric (Iwate)","04-tohoku":"Tohoku Electric (Miyagi)","05-tohoku":"Tohoku Electric (Akita)","06-tohoku":"Tohoku Electric (Yamagata)","07-tohoku":"Tohoku Electric (Fukushima)","08-tepco":"TEPCO (Ibaraki)","09-tepco":"TEPCO (Tochigi)","10-tepco":"TEPCO (Gunma)","11-tepco":"TEPCO (Saitama)","12-tepco":"TEPCO (Chiba)","13-tepco":"TEPCO (Tokyo)","14-tepco":"TEPCO (Kanagawa)","15-tohoku":"Tohoku Electric (Niigata)","16-hokuriku":"Hokuriku Electric (Toyama)","17-hokuriku":"Hokuriku Electric (Ishikawa)","18-kansai":"Kansai Electric (Fukui (Kansai Electric))","18-hokuriku":"Hokuriku Electric (Fukui (Hokuriku Electric))","19-tepco":"TEPCO (Yamanashi)","20-chubu":"Chubu Electric (Nagano)","21-chubu":"Chubu Electric (Gifu (Chubu Electric))","21-hokuriku":"Hokuriku Electric (Gifu (Hokuriku Electric))","21-kansai":"Kansai Electric (Gifu (Kansai Electric))","22-tepco":"TEPCO (Shizuoka (TEPCO))","22-chubu":"Chubu Electric (Shizuoka (Chubu Electric))","23-chubu":"Chubu Electric (Aichi)","24-chubu":"Chubu Electric (Mie (Chubu Electric))","24-kansai":"Kansai Electric (Mie (Kansai Electric))","25-kansai":"Kansai Electric (Shiga)","26-kansai":"Kansai Electric (Kyoto)","27-kansai":"Kansai Electric (Osaka)","28-kansai":"Kansai Electric (Hyogo (Kansai Electric))","28-chugoku":"Chugoku Electric (Hyogo (Chugoku Electric))","29-kansai":"Kansai Electric (Nara)","30-kansai":"Kansai Electric (Wakayama)","31-chugoku":"Chugoku Electric (Tottori)","32-chugoku":"Chugoku Electric (Shimane)","33-chugoku":"Chugoku Electric (Okayama)","34-chugoku":"Chugoku Electric (Hiroshima)","35-chugoku":"Chugoku Electric (Yamaguchi)","36-shikoku":"Shikoku Electric (Tokushima)","37-shikoku":"Shikoku Electric (Kagawa (Shikoku Electric))","37-chugoku":"Chugoku Electric (Kagawa (Chugoku Electric))","38-shikoku":"Shikoku Electric (Ehime (Shikoku Electric))","38-chugoku":"Chugoku Electric (Ehime (Chugoku Electric))","39-shikoku":"Shikoku Electric (Kochi)","40-kyushu":"Kyushu Electric (Fukuoka)","41-kyushu":"Kyushu Electric (Saga)","42-kyushu":"Kyushu Electric (Nagasaki)","43-kyushu":"Kyushu Electric (Kumamoto)","44-kyushu":"Kyushu Electric (Oita)","45-kyushu":"Kyushu Electric (Miyazaki)","46-kyushu":"Kyushu Electric (Kagoshima)","47-okinawa":"Okinawa Electric (Okinawa)"}},
    },
  ],
  g: "{@rg}",
  explore: {"t":{"code":"{kanji.name}","title":"{kanji.about0}","sub":["{kanji.about1}","{power.name}"]}},
};
