// South Korea Regions, on the map of ../south-korea-codes (each area a si-do or a
// part of one). The 17 si-do as before the 1 July 2026 Gwangju-Jeonnam merger, which is what coverage shows; Gunwi
// is in Daegu (since 2023). Kinds, coarse to fine: traditional regions, local-road prefixes, si-do in English, si-do
// in Hangul (short form as on plates, and the full official name).

const LAYERS = {
  key: "krregions",
  size: [1000,955],
  pad: 16,
  maxZoom: 40,
  labelScale: 0.25,
  fly: {"pad":1.6,"min":0.0375},
  street: {"bounds":[[33.1,124.6],[38.65,130.95]],"maxBounds":[[29,118],[43,137]]},
  hintLabel: "Color each si-do",
  exploreKind: "provinces",
  kinds: [
    {
      key: "regions",
      label: "Traditional regions",
      noun: ["region","regions"],
      prompt: "name",
      groups: [["Regions","",["CAP","GD","HS","YN","HN","JJ"]]],
      areas: {"x":{"CAP":["SE","IC","GG","GG-02","GG-032"],"GD":["GW"],"HS":["DJ","SJ","CB","CN","CN-042"],"YN":["BS","DG","DG-054","US","GB","GB-053","GN"],"HN":["GJ","JB","JN"],"JJ":["JJ"]}},
      name: {"x":{"CAP":"Sudogwon","GD":"Gwandong","HS":"Hoseo","YN":"Yeongnam","HN":"Honam","JJ":"Jeju"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"CAP":"Seoul, Incheon, Gyeonggi","GD":"Gangwon","HS":"Chungcheong","YN":"Gyeongsang","HN":"Jeolla","JJ":"Jeju"}},
      about: {"x":{"CAP":["수도권 · Seoul, Incheon, Gyeonggi"],"GD":["관동 · Gangwon"],"HS":["호서 · Chungcheong"],"YN":["영남 · Gyeongsang"],"HN":["호남 · Jeolla"],"JJ":["제주 · Jeju"]}},
      clicked: {"x":{"SE":"Seoul (Sudogwon)","BS":"Busan (Yeongnam)","DG":"Daegu (Yeongnam)","IC":"Incheon (Sudogwon)","GJ":"Gwangju (Honam)","DJ":"Daejeon (Hoseo)","US":"Ulsan (Yeongnam)","SJ":"Sejong (Hoseo)","GG":"Gyeonggi (Sudogwon)","GG-02":"Gyeonggi (Sudogwon)","GG-032":"Gyeonggi (Sudogwon)","GW":"Gangwon (Gwandong)","CB":"North Chungcheong (Hoseo)","CN":"South Chungcheong (Hoseo)","CN-042":"South Chungcheong (Hoseo)","JN":"South Jeolla (Honam)","GB":"North Gyeongsang (Yeongnam)","GB-053":"North Gyeongsang (Yeongnam)","DG-054":"Daegu (Yeongnam)","GN":"South Gyeongsang (Yeongnam)","JJ":"Jeju (Jeju)","JB":"North Jeolla (Honam)"}},
    },
    {
      key: "roads",
      label: "Local-road prefixes",
      noun: ["prefix","prefixes"],
      prompt: "text",
      groups: [["Local roads (지방도)","",["3","4","5","6","7","8","9","10","11"]]],
      areas: {"x":{"3":["GG","GG-02","GG-032"],"4":["GW"],"5":["CB"],"6":["CN","CN-042"],"7":["JB"],"8":["JN"],"9":["GB","GB-053"],"10":["GN"],"11":["JJ"]}},
      name: "{id}xx",
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"3":"Gyeonggi","4":"Gangwon","5":"North Chungcheong","6":"South Chungcheong","7":"North Jeolla","8":"South Jeolla","9":"North Gyeongsang","10":"South Gyeongsang","11":"Jeju"}},
      about: {"x":{"3":["Gyeonggi","경기도"],"4":["Gangwon","강원특별자치도 (강원도)"],"5":["North Chungcheong","충청북도"],"6":["South Chungcheong","충청남도"],"7":["North Jeolla","전북특별자치도 (전라북도)"],"8":["South Jeolla","전라남도"],"9":["North Gyeongsang","경상북도"],"10":["South Gyeongsang","경상남도"],"11":["Jeju","제주특별자치도"]}},
      text: {"t":{"text":"{name}","cls":"shield"}},
      clicked: {"t":"{name} ({chipTitle})","x":{"SE":"Seoul: no local roads","BS":"Busan: no local roads","DG":"Daegu: no local roads","IC":"Incheon: no local roads","GJ":"Gwangju: no local roads","DJ":"Daejeon: no local roads","US":"Ulsan: no local roads","SJ":"Sejong: no local roads","DG-054":"Daegu: no local roads"}},
    },
    {
      key: "provinces",
      label: "Si-do",
      noun: ["si-do","si-do"],
      prompt: "name",
      lang: "English",
      groups: [["Sudogwon","Seoul, Incheon, Gyeonggi",["SE","IC","GG"]],["Gwandong","Gangwon",["GW"]],["Hoseo","Chungcheong",["DJ","SJ","CB","CN"]],["Yeongnam","Gyeongsang",["BS","DG","US","GB","GN"]],["Honam","Jeolla",["GJ","JB","JN"]],["Jeju","Jeju",["JJ"]]],
      areas: "@sido",
      name: {"x":{"SE":"Seoul","IC":"Incheon","GG":"Gyeonggi","GW":"Gangwon","DJ":"Daejeon","SJ":"Sejong","CB":"North Chungcheong","CN":"South Chungcheong","BS":"Busan","DG":"Daegu","US":"Ulsan","GB":"North Gyeongsang","GN":"South Gyeongsang","GJ":"Gwangju","JB":"North Jeolla","JN":"South Jeolla","JJ":"Jeju"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"SE":"서울","IC":"인천","GG":"경기","GW":"강원","DJ":"대전","SJ":"세종","CB":"충북","CN":"충남","BS":"부산","DG":"대구","US":"울산","GB":"경북","GN":"경남","GJ":"광주","JB":"전북","JN":"전남","JJ":"제주"}},
      about: {"x":{"SE":["서울특별시","Sudogwon · 02"],"IC":["인천광역시","Sudogwon · 032"],"GG":["경기도","Sudogwon · 031, 02, 032"],"GW":["강원특별자치도 (강원도)","Gwandong · 033"],"DJ":["대전광역시","Hoseo · 042"],"SJ":["세종특별자치시","Hoseo · 044"],"CB":["충청북도","Hoseo · 043"],"CN":["충청남도","Hoseo · 041, 042"],"BS":["부산광역시","Yeongnam · 051"],"DG":["대구광역시","Yeongnam · 053, 054"],"US":["울산광역시","Yeongnam · 052"],"GB":["경상북도","Yeongnam · 054, 053"],"GN":["경상남도","Yeongnam · 055"],"GJ":["광주광역시","Honam · 062"],"JB":["전북특별자치도 (전라북도)","Honam · 063"],"JN":["전라남도","Honam · 061"],"JJ":["제주특별자치도","Jeju · 064"]}},
      clicked: "{name}",
    },
    {
      key: "hangul",
      label: "Hangul",
      noun: ["si-do","si-do"],
      prompt: "text",
      of: "provinces",
      lang: "Korean",
      groups: [["Sudogwon","Seoul, Incheon, Gyeonggi",["SE","IC","GG"]],["Gwandong","Gangwon",["GW"]],["Hoseo","Chungcheong",["DJ","SJ","CB","CN"]],["Yeongnam","Gyeongsang",["BS","DG","US","GB","GN"]],["Honam","Jeolla",["GJ","JB","JN"]],["Jeju","Jeju",["JJ"]]],
      areas: "@sido",
      name: {"x":{"SE":"서울","IC":"인천","GG":"경기","GW":"강원","DJ":"대전","SJ":"세종","CB":"충북","CN":"충남","BS":"부산","DG":"대구","US":"울산","GB":"경북","GN":"경남","GJ":"광주","JB":"전북","JN":"전남","JJ":"제주"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"SE":"Seoul","IC":"Incheon","GG":"Gyeonggi","GW":"Gangwon","DJ":"Daejeon","SJ":"Sejong","CB":"North Chungcheong","CN":"South Chungcheong","BS":"Busan","DG":"Daegu","US":"Ulsan","GB":"North Gyeongsang","GN":"South Gyeongsang","GJ":"Gwangju","JB":"North Jeolla","JN":"South Jeolla","JJ":"Jeju"}},
      about: {"x":{"SE":["Seoul","서울특별시","Sudogwon · 02"],"IC":["Incheon","인천광역시","Sudogwon · 032"],"GG":["Gyeonggi","경기도","Sudogwon · 031, 02, 032"],"GW":["Gangwon","강원특별자치도 (강원도)","Gwandong · 033"],"DJ":["Daejeon","대전광역시","Hoseo · 042"],"SJ":["Sejong","세종특별자치시","Hoseo · 044"],"CB":["North Chungcheong","충청북도","Hoseo · 043"],"CN":["South Chungcheong","충청남도","Hoseo · 041, 042"],"BS":["Busan","부산광역시","Yeongnam · 051"],"DG":["Daegu","대구광역시","Yeongnam · 053, 054"],"US":["Ulsan","울산광역시","Yeongnam · 052"],"GB":["North Gyeongsang","경상북도","Yeongnam · 054, 053"],"GN":["South Gyeongsang","경상남도","Yeongnam · 055"],"GJ":["Gwangju","광주광역시","Honam · 062"],"JB":["North Jeolla","전북특별자치도 (전라북도)","Honam · 063"],"JN":["South Jeolla","전라남도","Honam · 061"],"JJ":["Jeju","제주특별자치도","Jeju · 064"]}},
      text: {"t":{"text":"{name}","lang":"ko","cls":"ko"}},
      clicked: "{name} · {chipTitle}",
    },
    {
      key: "hangulfull",
      label: "Hangul full names",
      noun: ["si-do","si-do"],
      prompt: "text",
      of: "provinces",
      lang: "Korean, full",
      groups: [["Sudogwon","Seoul, Incheon, Gyeonggi",["SE","IC","GG"]],["Gwandong","Gangwon",["GW"]],["Hoseo","Chungcheong",["DJ","SJ","CB","CN"]],["Yeongnam","Gyeongsang",["BS","DG","US","GB","GN"]],["Honam","Jeolla",["GJ","JB","JN"]],["Jeju","Jeju",["JJ"]]],
      areas: "@sido",
      name: {"x":{"SE":"서울특별시","IC":"인천광역시","GG":"경기도","GW":"강원특별자치도","DJ":"대전광역시","SJ":"세종특별자치시","CB":"충청북도","CN":"충청남도","BS":"부산광역시","DG":"대구광역시","US":"울산광역시","GB":"경상북도","GN":"경상남도","GJ":"광주광역시","JB":"전북특별자치도","JN":"전라남도","JJ":"제주특별자치도"}},
      short: {"x":{"SE":"서울","IC":"인천","GG":"경기","GW":"강원","DJ":"대전","SJ":"세종","CB":"충북","CN":"충남","BS":"부산","DG":"대구","US":"울산","GB":"경북","GN":"경남","GJ":"광주","JB":"전북","JN":"전남","JJ":"제주"}},
      chip: "{name}",
      chipTitle: {"x":{"SE":"Seoul","IC":"Incheon","GG":"Gyeonggi","GW":"Gangwon","DJ":"Daejeon","SJ":"Sejong","CB":"North Chungcheong","CN":"South Chungcheong","BS":"Busan","DG":"Daegu","US":"Ulsan","GB":"North Gyeongsang","GN":"South Gyeongsang","GJ":"Gwangju","JB":"North Jeolla","JN":"South Jeolla","JJ":"Jeju"}},
      about: {"t":["{chipTitle}","{name}","{group} · {@code}"],"x":{"GW":["Gangwon","강원특별자치도 (강원도)","Gwandong · 033"],"JB":["North Jeolla","전북특별자치도 (전라북도)","Honam · 063"],"GG":["Gyeonggi","경기도","Sudogwon · 031, 02, 032"],"CN":["South Chungcheong","충청남도","Hoseo · 041, 042"],"DG":["Daegu","대구광역시","Yeongnam · 053, 054"],"GB":["North Gyeongsang","경상북도","Yeongnam · 054, 053"]}},
      text: {"t":{"text":"{name}","lang":"ko","cls":"ko"}},
      clicked: "{name} · {chipTitle}",
    },
  ],
  g: "{@sido}",
  explore: {"t":{"code":"{hangul.name}","title":"{hangul.about0}","sub":["{hangul.about1}","{regions.name} · Local roads {roads.name}"]},"x":{"SE":{"code":"서울","title":"Seoul","sub":["서울특별시","Sudogwon"]},"BS":{"code":"부산","title":"Busan","sub":["부산광역시","Yeongnam"]},"DG":{"code":"대구","title":"Daegu","sub":["대구광역시","Yeongnam"]},"IC":{"code":"인천","title":"Incheon","sub":["인천광역시","Sudogwon"]},"GJ":{"code":"광주","title":"Gwangju","sub":["광주광역시","Honam"]},"DJ":{"code":"대전","title":"Daejeon","sub":["대전광역시","Hoseo"]},"US":{"code":"울산","title":"Ulsan","sub":["울산광역시","Yeongnam"]},"SJ":{"code":"세종","title":"Sejong","sub":["세종특별자치시","Hoseo"]},"DG-054":{"code":"대구","title":"Daegu","sub":["대구광역시","Yeongnam"]}}},
};
