// Cambodia Provinces. Map areas: the 24 provinces and Phnom Penh (geoBoundaries ADM1,
// ids are ISO 3166-2 codes). Kinds: the four census regions, provinces by English name and in Khmer script, and
// "Roads & signs": the national highways 1–8 (every province each one runs through, from OpenStreetMap) and the
// Khmer–Chinese shop signs of Preah Sihanouk.

const LAYERS = {
  key: "khprov",
  size: [1000,929],
  pad: 16,
  maxZoom: 40,
  labelScale: 0.3,
  fly: {"pad":1.6,"min":0.0375},
  street: {"bounds":[[10.4,102.3],[14.7,107.7]],"maxBounds":[[6,98],[19,112]]},
  hintLabel: "Color by census region",
  exploreKind: "provinces",
  kinds: [
    {
      key: "provinces",
      label: "Provinces",
      noun: ["province","provinces"],
      prompt: "name",
      lang: "English",
      groups: [["Central Plain","",["KH-3","KH-8","KH-12","KH-14","KH-20","KH-21","KH-25"]],["Tonle Sap","",["KH-1","KH-2","KH-4","KH-6","KH-22","KH-24","KH-15","KH-17"]],["Coastal and Sea","",["KH-7","KH-23","KH-9","KH-18"]],["Plateau and Mountains","",["KH-5","KH-10","KH-11","KH-13","KH-16","KH-19"]]],
      areas: "@id",
      name: "{@name}",
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"KH-3":"កំពង់ចាម","KH-8":"កណ្ដាល","KH-12":"ភ្នំពេញ","KH-14":"ព្រៃវែង","KH-20":"ស្វាយរៀង","KH-21":"តាកែវ","KH-25":"ត្បូងឃ្មុំ","KH-1":"បន្ទាយមានជ័យ","KH-2":"បាត់ដំបង","KH-4":"កំពង់ឆ្នាំង","KH-6":"កំពង់ធំ","KH-22":"ឧត្ដរមានជ័យ","KH-24":"ប៉ៃលិន","KH-15":"ពោធិ៍សាត់","KH-17":"សៀមរាប","KH-7":"កំពត","KH-23":"កែប","KH-9":"កោះកុង","KH-18":"ព្រះសីហនុ","KH-5":"កំពង់ស្ពឺ","KH-10":"ក្រចេះ","KH-11":"មណ្ឌលគិរី","KH-13":"ព្រះវិហារ","KH-16":"រតនគិរី","KH-19":"ស្ទឹងត្រែង"}},
      about: {"x":{"KH-3":["Central Plain · 895,763 people","NR 6, 7"],"KH-8":["Central Plain · 1,195,547 people","NR 1, 2, 3, 4, 5, 6, 8"],"KH-12":["Central Plain · 2,129,371 people","NR 1, 2, 3, 4, 5, 6"],"KH-14":["Central Plain · 1,057,428 people","NR 1, 8"],"KH-20":["Central Plain · 524,554 people","NR 1"],"KH-21":["Central Plain · 899,485 people","NR 2, 3"],"KH-25":["Central Plain · 775,296 people","NR 7, 8"],"KH-1":["Tonle Sap · 859,545 people","NR 5, 6"],"KH-2":["Tonle Sap · 987,400 people","NR 5"],"KH-4":["Tonle Sap · 525,932 people","NR 5"],"KH-6":["Tonle Sap · 677,260 people","NR 6"],"KH-22":["Tonle Sap · 261,252 people"],"KH-24":["Tonle Sap · 71,600 people"],"KH-15":["Tonle Sap · 411,759 people","NR 5"],"KH-17":["Tonle Sap · 1,006,512 people","NR 6"],"KH-7":["Coastal and Sea · 592,845 people","NR 3"],"KH-23":["Coastal and Sea · 41,798 people"],"KH-9":["Coastal and Sea · 123,618 people"],"KH-18":["Coastal and Sea · 302,887 people","NR 3, 4"],"KH-5":["Plateau and Mountains · 872,219 people","NR 4"],"KH-10":["Plateau and Mountains · 372,825 people","NR 7"],"KH-11":["Plateau and Mountains · 88,649 people"],"KH-13":["Plateau and Mountains · 251,352 people"],"KH-16":["Plateau and Mountains · 204,027 people"],"KH-19":["Plateau and Mountains · 159,565 people","NR 7"]}},
      clicked: "{name}",
      rankings: [["population",["KH-12","KH-8","KH-14","KH-17","KH-2","KH-21","KH-3","KH-5","KH-1","KH-25","KH-6","KH-7","KH-4","KH-20","KH-15","KH-10","KH-18","KH-22","KH-13","KH-16","KH-19","KH-9","KH-11","KH-24","KH-23"]]],
    },
    {
      key: "khmer",
      label: "Khmer script",
      noun: ["province","provinces"],
      prompt: "text",
      of: "provinces",
      lang: "Khmer",
      groups: [["Central Plain","",["KH-3","KH-8","KH-12","KH-14","KH-20","KH-21","KH-25"]],["Tonle Sap","",["KH-1","KH-2","KH-4","KH-6","KH-22","KH-24","KH-15","KH-17"]],["Coastal and Sea","",["KH-7","KH-23","KH-9","KH-18"]],["Plateau and Mountains","",["KH-5","KH-10","KH-11","KH-13","KH-16","KH-19"]]],
      areas: "@id",
      name: {"x":{"KH-3":"កំពង់ចាម · Kampong Cham","KH-8":"កណ្ដាល · Kandal","KH-12":"ភ្នំពេញ · Phnom Penh","KH-14":"ព្រៃវែង · Prey Veng","KH-20":"ស្វាយរៀង · Svay Rieng","KH-21":"តាកែវ · Takeo","KH-25":"ត្បូងឃ្មុំ · Tbong Khmum","KH-1":"បន្ទាយមានជ័យ · Banteay Meanchey","KH-2":"បាត់ដំបង · Battambang","KH-4":"កំពង់ឆ្នាំង · Kampong Chhnang","KH-6":"កំពង់ធំ · Kampong Thom","KH-22":"ឧត្ដរមានជ័យ · Oddar Meanchey","KH-24":"ប៉ៃលិន · Pailin","KH-15":"ពោធិ៍សាត់ · Pursat","KH-17":"សៀមរាប · Siem Reap","KH-7":"កំពត · Kampot","KH-23":"កែប · Kep","KH-9":"កោះកុង · Koh Kong","KH-18":"ព្រះសីហនុ · Preah Sihanouk","KH-5":"កំពង់ស្ពឺ · Kampong Speu","KH-10":"ក្រចេះ · Kratie","KH-11":"មណ្ឌលគិរី · Mondulkiri","KH-13":"ព្រះវិហារ · Preah Vihear","KH-16":"រតនគិរី · Ratanakiri","KH-19":"ស្ទឹងត្រែង · Stung Treng"}},
      short: {"x":{"KH-3":"កំពង់ចាម","KH-8":"កណ្ដាល","KH-12":"ភ្នំពេញ","KH-14":"ព្រៃវែង","KH-20":"ស្វាយរៀង","KH-21":"តាកែវ","KH-25":"ត្បូងឃ្មុំ","KH-1":"បន្ទាយមានជ័យ","KH-2":"បាត់ដំបង","KH-4":"កំពង់ឆ្នាំង","KH-6":"កំពង់ធំ","KH-22":"ឧត្ដរមានជ័យ","KH-24":"ប៉ៃលិន","KH-15":"ពោធិ៍សាត់","KH-17":"សៀមរាប","KH-7":"កំពត","KH-23":"កែប","KH-9":"កោះកុង","KH-18":"ព្រះសីហនុ","KH-5":"កំពង់ស្ពឺ","KH-10":"ក្រចេះ","KH-11":"មណ្ឌលគិរី","KH-13":"ព្រះវិហារ","KH-16":"រតនគិរី","KH-19":"ស្ទឹងត្រែង"}},
      chip: "{short}",
      chipTitle: "{@name}",
      about: {"x":{"KH-3":["Central Plain · 895,763 people","NR 6, 7"],"KH-8":["Central Plain · 1,195,547 people","NR 1, 2, 3, 4, 5, 6, 8"],"KH-12":["Central Plain · 2,129,371 people","NR 1, 2, 3, 4, 5, 6"],"KH-14":["Central Plain · 1,057,428 people","NR 1, 8"],"KH-20":["Central Plain · 524,554 people","NR 1"],"KH-21":["Central Plain · 899,485 people","NR 2, 3"],"KH-25":["Central Plain · 775,296 people","NR 7, 8"],"KH-1":["Tonle Sap · 859,545 people","NR 5, 6"],"KH-2":["Tonle Sap · 987,400 people","NR 5"],"KH-4":["Tonle Sap · 525,932 people","NR 5"],"KH-6":["Tonle Sap · 677,260 people","NR 6"],"KH-22":["Tonle Sap · 261,252 people"],"KH-24":["Tonle Sap · 71,600 people"],"KH-15":["Tonle Sap · 411,759 people","NR 5"],"KH-17":["Tonle Sap · 1,006,512 people","NR 6"],"KH-7":["Coastal and Sea · 592,845 people","NR 3"],"KH-23":["Coastal and Sea · 41,798 people"],"KH-9":["Coastal and Sea · 123,618 people"],"KH-18":["Coastal and Sea · 302,887 people","NR 3, 4"],"KH-5":["Plateau and Mountains · 872,219 people","NR 4"],"KH-10":["Plateau and Mountains · 372,825 people","NR 7"],"KH-11":["Plateau and Mountains · 88,649 people"],"KH-13":["Plateau and Mountains · 251,352 people"],"KH-16":["Plateau and Mountains · 204,027 people"],"KH-19":["Plateau and Mountains · 159,565 people","NR 7"]}},
      text: {"t":{"text":"{chip}","lang":"km","cls":"km"}},
      clicked: "{name}",
      rankings: [["population",["KH-12","KH-8","KH-14","KH-17","KH-2","KH-21","KH-3","KH-5","KH-1","KH-25","KH-6","KH-7","KH-4","KH-20","KH-15","KH-10","KH-18","KH-22","KH-13","KH-16","KH-19","KH-9","KH-11","KH-24","KH-23"]]],
    },
    {
      key: "zones",
      label: "Census regions",
      noun: ["region","regions"],
      prompt: "name",
      hints: false,
      groups: [["Census regions","2019 census",["CP","TS","CS","PM"]]],
      areas: "@zone",
      name: {"x":{"CP":"Central Plain","TS":"Tonle Sap","CS":"Coastal and Sea","PM":"Plateau and Mountains"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"CP":"7 provinces","TS":"8 provinces","CS":"4 provinces","PM":"6 provinces"}},
      about: {"x":{"CP":"Kampong Cham, Kandal, Phnom Penh, Prey Veng, Svay Rieng, Takeo, Tbong Khmum","TS":"Banteay Meanchey, Battambang, Kampong Chhnang, Kampong Thom, Oddar Meanchey, Pailin, Pursat, Siem Reap","CS":"Kampot, Kep, Koh Kong, Preah Sihanouk","PM":"Kampong Speu, Kratie, Mondulkiri, Preah Vihear, Ratanakiri, Stung Treng"}},
      clicked: "{@name} · {name}",
    },
    {
      key: "clues",
      label: "Roads & signs",
      noun: ["clue","clues"],
      prompt: "text",
      clickAll: true,
      merge: false,
      groups: [["National roads","every province on the road",["nr1","nr2","nr3","nr4","nr5","nr6","nr7","nr8"]],["Signs","",["zh"]]],
      areas: {"x":{"nr1":["KH-12","KH-8","KH-14","KH-20"],"nr2":["KH-12","KH-8","KH-21"],"nr3":["KH-12","KH-8","KH-21","KH-7","KH-18"],"nr4":["KH-12","KH-8","KH-5","KH-18"],"nr5":["KH-12","KH-8","KH-4","KH-15","KH-2","KH-1"],"nr6":["KH-12","KH-8","KH-3","KH-6","KH-17","KH-1"],"nr7":["KH-3","KH-25","KH-10","KH-19"],"nr8":["KH-8","KH-14","KH-25"],"zh":["KH-18"]}},
      name: {"x":{"nr1":"National Road 1","nr2":"National Road 2","nr3":"National Road 3","nr4":"National Road 4","nr5":"National Road 5","nr6":"National Road 6","nr7":"National Road 7","nr8":"National Road 8","zh":"Khmer–Chinese signs"}},
      short: {"x":{"nr1":"NR1","nr2":"NR2","nr3":"NR3","nr4":"NR4","nr5":"NR5","nr6":"NR6","nr7":"NR7","nr8":"NR8","zh":"中文"}},
      chip: "{short}",
      chipTitle: {"x":{"nr1":"Phnom Penh → Bavet","nr2":"Phnom Penh → Phnom Den","nr3":"Phnom Penh → Kampot → Veal Renh","nr4":"Phnom Penh → Sihanoukville","nr5":"Phnom Penh → Battambang → Poipet","nr6":"Phnom Penh → Skun → Siem Reap → Sisophon","nr7":"Skun → Kratie → Stung Treng","nr8":"Prek Tamak → Tbong Khmum","zh":"Khmer–Chinese signs"}},
      about: {"x":{"nr1":["Phnom Penh → Bavet","Phnom Penh, Kandal, Prey Veng, Svay Rieng"],"nr2":["Phnom Penh → Phnom Den","Phnom Penh, Kandal, Takeo"],"nr3":["Phnom Penh → Kampot → Veal Renh","Phnom Penh, Kandal, Takeo, Kampot, Preah Sihanouk"],"nr4":["Phnom Penh → Sihanoukville","Phnom Penh, Kandal, Kampong Speu, Preah Sihanouk"],"nr5":["Phnom Penh → Battambang → Poipet","Phnom Penh, Kandal, Kampong Chhnang, Pursat, Battambang, Banteay Meanchey"],"nr6":["Phnom Penh → Skun → Siem Reap → Sisophon","Phnom Penh, Kandal, Kampong Cham, Kampong Thom, Siem Reap, Banteay Meanchey"],"nr7":["Skun → Kratie → Stung Treng","Kampong Cham, Tbong Khmum, Kratie, Stung Treng"],"nr8":["Prek Tamak → Tbong Khmum","Kandal, Prey Veng, Tbong Khmum"],"zh":["Preah Sihanouk","Sihanoukville"]}},
      text: {"x":{"nr1":{"text":"1","cls":"stone"},"nr2":{"text":"2","cls":"stone"},"nr3":{"text":"3","cls":"stone"},"nr4":{"text":"4","cls":"stone"},"nr5":{"text":"5","cls":"stone"},"nr6":{"text":"6","cls":"stone"},"nr7":{"text":"7","cls":"stone"},"nr8":{"text":"8","cls":"stone"},"zh":{"text":"ភោជនីយដ្ឋាន\n中餐厅","cls":"zh","lang":"km"}}},
      clicked: {"x":{"KH-19":"Stung Treng · NR 7","KH-13":"Preah Vihear","KH-6":"Kampong Thom · NR 6","KH-12":"Phnom Penh · NR 1, 2, 3, 4, 5, 6","KH-9":"Koh Kong","KH-23":"Kep","KH-7":"Kampot · NR 3","KH-21":"Takeo · NR 2, 3","KH-8":"Kandal · NR 1, 2, 3, 4, 5, 6, 8","KH-15":"Pursat · NR 5","KH-16":"Ratanakiri","KH-4":"Kampong Chhnang · NR 5","KH-24":"Pailin","KH-1":"Banteay Meanchey · NR 5, 6","KH-17":"Siem Reap · NR 6","KH-22":"Oddar Meanchey","KH-3":"Kampong Cham · NR 6, 7","KH-11":"Mondulkiri","KH-10":"Kratie · NR 7","KH-14":"Prey Veng · NR 1, 8","KH-5":"Kampong Speu · NR 4","KH-20":"Svay Rieng · NR 1","KH-18":"Preah Sihanouk · NR 3, 4","KH-25":"Tbong Khmum · NR 7, 8","KH-2":"Battambang · NR 5"}},
    },
  ],
  g: "{@zone}",
  explore: {"t":{"code":"{khmer.chip}","title":"{@name}","sub":["{khmer.about0}","{khmer.about1}"]},"x":{"KH-13":{"code":"ព្រះវិហារ","title":"Preah Vihear","sub":["Plateau and Mountains · 251,352 people"]},"KH-9":{"code":"កោះកុង","title":"Koh Kong","sub":["Coastal and Sea · 123,618 people"]},"KH-23":{"code":"កែប","title":"Kep","sub":["Coastal and Sea · 41,798 people"]},"KH-16":{"code":"រតនគិរី","title":"Ratanakiri","sub":["Plateau and Mountains · 204,027 people"]},"KH-24":{"code":"ប៉ៃលិន","title":"Pailin","sub":["Tonle Sap · 71,600 people"]},"KH-22":{"code":"ឧត្ដរមានជ័យ","title":"Oddar Meanchey","sub":["Tonle Sap · 261,252 people"]},"KH-11":{"code":"មណ្ឌលគិរី","title":"Mondulkiri","sub":["Plateau and Mountains · 88,649 people"]}}},
};
