// Ukraine Regions, on the map of ../ukraine-codes (24 oblasts, the Autonomous
// Republic of Crimea, Kyiv and Sevastopol; names and codes in ../ukraine-codes/names.js). Kinds, coarse to fine:
// macro-regions (KIIS, unofficial; they only group the oblasts), oblasts in English and oblasts in Ukrainian (Cyrillic). ../ukraine-roads uses the
// same config for the region index in territorial road numbers (T-xx-yy, CMU Resolution 1318/2023).

const LAYERS = {
  key: "uaregions",
  size: [1000,690],
  pad: 16,
  maxZoom: 40,
  labelScale: 0.25,
  fly: {"pad":1.6,"min":0.0375},
  street: {"bounds":[[44.38,22.14],[52.38,40.23]],"maxBounds":[[40,15],[57,47]]},
  hintLabel: "Color each oblast",
  exploreKind: "oblasts",
  kinds: [
    {
      key: "macro",
      label: "Macro-regions",
      groupsOnly: true,
      noun: ["region","regions"],
      prompt: "name",
      groups: [["Macro-regions","",["W","C","S","E","CR"]]],
      areas: {"x":{"W":["volyn","zakarpattia","ivanofrankivsk","lviv","rivne","ternopil","khmelnytskyi","chernivtsi"],"C":["vinnytsia","zhytomyr","kyivoblast","kyiv","kirovohrad","poltava","sumy","cherkasy","chernihiv"],"S":["dnipropetrovsk","zaporizhzhia","mykolaiv","odesa","kherson"],"E":["donetsk","luhansk","kharkiv"],"CR":["crimea","sevastopol"]}},
      name: {"x":{"W":"West","C":"Centre","S":"South","E":"East","CR":"Crimea"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"W":"Volyn, Zakarpattia, Ivano-Frankivsk, Lviv, Rivne, Ternopil, Khmelnytskyi, Chernivtsi","C":"Vinnytsia, Zhytomyr, Kyiv Oblast, Kyiv City, Kirovohrad, Poltava, Sumy, Cherkasy, Chernihiv","S":"Dnipropetrovsk, Zaporizhzhia, Mykolaiv, Odesa, Kherson","E":"Donetsk, Luhansk, Kharkiv","CR":"Crimea, Sevastopol"}},
      about: {"t":["{chipTitle}"]},
      clicked: {"x":{"kherson":"Kherson (South)","volyn":"Volyn (West)","rivne":"Rivne (West)","zhytomyr":"Zhytomyr (Centre)","kyivoblast":"Kyiv Oblast (Centre)","chernihiv":"Chernihiv (Centre)","sumy":"Sumy (Centre)","kharkiv":"Kharkiv (East)","luhansk":"Luhansk (East)","donetsk":"Donetsk (East)","zaporizhzhia":"Zaporizhzhia (South)","lviv":"Lviv (West)","ivanofrankivsk":"Ivano-Frankivsk (West)","zakarpattia":"Zakarpattia (West)","ternopil":"Ternopil (West)","chernivtsi":"Chernivtsi (West)","odesa":"Odesa (South)","mykolaiv":"Mykolaiv (South)","crimea":"Crimea (Crimea)","vinnytsia":"Vinnytsia (Centre)","khmelnytskyi":"Khmelnytskyi (West)","cherkasy":"Cherkasy (Centre)","poltava":"Poltava (Centre)","dnipropetrovsk":"Dnipropetrovsk (South)","kirovohrad":"Kirovohrad (Centre)","kyiv":"Kyiv City (Centre)","sevastopol":"Sevastopol (Crimea)"}},
    },
    {
      key: "oblasts",
      label: "Oblasts",
      noun: ["oblast","oblasts"],
      prompt: "name",
      lang: "English",
      groups: [["West","",["volyn","zakarpattia","ivanofrankivsk","lviv","rivne","ternopil","khmelnytskyi","chernivtsi"]],["Centre","",["vinnytsia","zhytomyr","kyivoblast","kyiv","kirovohrad","poltava","sumy","cherkasy","chernihiv"]],["South","",["dnipropetrovsk","zaporizhzhia","mykolaiv","odesa","kherson"]],["East","",["donetsk","luhansk","kharkiv"]],["Crimea","",["crimea","sevastopol"]]],
      areas: "@id",
      name: {"x":{"volyn":"Volyn","zakarpattia":"Zakarpattia","ivanofrankivsk":"Ivano-Frankivsk","lviv":"Lviv","rivne":"Rivne","ternopil":"Ternopil","khmelnytskyi":"Khmelnytskyi","chernivtsi":"Chernivtsi","vinnytsia":"Vinnytsia","zhytomyr":"Zhytomyr","kyivoblast":"Kyiv Oblast","kyiv":"Kyiv City","kirovohrad":"Kirovohrad","poltava":"Poltava","sumy":"Sumy","cherkasy":"Cherkasy","chernihiv":"Chernihiv","dnipropetrovsk":"Dnipropetrovsk","zaporizhzhia":"Zaporizhzhia","mykolaiv":"Mykolaiv","odesa":"Odesa","kherson":"Kherson","donetsk":"Donetsk","luhansk":"Luhansk","kharkiv":"Kharkiv","crimea":"Crimea","sevastopol":"Sevastopol"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"volyn":"Волинська область","zakarpattia":"Закарпатська область","ivanofrankivsk":"Івано-Франківська область","lviv":"Львівська область","rivne":"Рівненська область","ternopil":"Тернопільська область","khmelnytskyi":"Хмельницька область","chernivtsi":"Чернівецька область","vinnytsia":"Вінницька область","zhytomyr":"Житомирська область","kyivoblast":"Київська область","kyiv":"м. Київ","kirovohrad":"Кіровоградська область","poltava":"Полтавська область","sumy":"Сумська область","cherkasy":"Черкаська область","chernihiv":"Чернігівська область","dnipropetrovsk":"Дніпропетровська область","zaporizhzhia":"Запорізька область","mykolaiv":"Миколаївська область","odesa":"Одеська область","kherson":"Херсонська область","donetsk":"Донецька область","luhansk":"Луганська область","kharkiv":"Харківська область","crimea":"Автономна Республіка Крим","sevastopol":"м. Севастополь"}},
      about: {"x":{"volyn":["Volyn","Волинська область","033 · T-03"],"zakarpattia":["Zakarpattia","Закарпатська область","031 · T-07"],"ivanofrankivsk":["Ivano-Frankivsk","Івано-Франківська область","034 · T-09"],"lviv":["Lviv","Львівська область","032 · T-14"],"rivne":["Rivne","Рівненська область","036 · T-18"],"ternopil":["Ternopil","Тернопільська область","035 · T-20"],"khmelnytskyi":["Khmelnytskyi","Хмельницька область","038 · T-23"],"chernivtsi":["Chernivtsi","Чернівецька область","037 · T-26"],"vinnytsia":["Vinnytsia","Вінницька область","043 · T-02"],"zhytomyr":["Zhytomyr","Житомирська область","041 · T-06"],"kyivoblast":["Kyiv Oblast","Київська область","045 · T-10"],"kyiv":["Kyiv City","м. Київ","044 · no T roads"],"kirovohrad":["Kirovohrad","Кіровоградська область","052 · T-12"],"poltava":["Poltava","Полтавська область","053 · T-17"],"sumy":["Sumy","Сумська область","054 · T-19"],"cherkasy":["Cherkasy","Черкаська область","047 · T-24"],"chernihiv":["Chernihiv","Чернігівська область","046 · T-25"],"dnipropetrovsk":["Dnipropetrovsk","Дніпропетровська область","056 · T-04"],"zaporizhzhia":["Zaporizhzhia","Запорізька область","061 · T-08"],"mykolaiv":["Mykolaiv","Миколаївська область","051 · T-15"],"odesa":["Odesa","Одеська область","048 · T-16"],"kherson":["Kherson","Херсонська область","055 · T-22"],"donetsk":["Donetsk","Донецька область","062 · T-05"],"luhansk":["Luhansk","Луганська область","064 · T-13"],"kharkiv":["Kharkiv","Харківська область","057 · T-21"],"crimea":["Crimea","Автономна Республіка Крим","065 · T-01"],"sevastopol":["Sevastopol","м. Севастополь","069 · T-27"]}},
      clicked: "{name}",
    },
    {
      key: "cyrillic",
      label: "Cyrillic",
      noun: ["oblast","oblasts"],
      prompt: "text",
      of: "oblasts",
      lang: "Ukrainian",
      groups: [["West","",["volyn","zakarpattia","ivanofrankivsk","lviv","rivne","ternopil","khmelnytskyi","chernivtsi"]],["Centre","",["vinnytsia","zhytomyr","kyivoblast","kyiv","kirovohrad","poltava","sumy","cherkasy","chernihiv"]],["South","",["dnipropetrovsk","zaporizhzhia","mykolaiv","odesa","kherson"]],["East","",["donetsk","luhansk","kharkiv"]],["Crimea","",["crimea","sevastopol"]]],
      areas: "@id",
      name: {"x":{"volyn":"Волинська область","zakarpattia":"Закарпатська область","ivanofrankivsk":"Івано-Франківська область","lviv":"Львівська область","rivne":"Рівненська область","ternopil":"Тернопільська область","khmelnytskyi":"Хмельницька область","chernivtsi":"Чернівецька область","vinnytsia":"Вінницька область","zhytomyr":"Житомирська область","kyivoblast":"Київська область","kyiv":"м. Київ","kirovohrad":"Кіровоградська область","poltava":"Полтавська область","sumy":"Сумська область","cherkasy":"Черкаська область","chernihiv":"Чернігівська область","dnipropetrovsk":"Дніпропетровська область","zaporizhzhia":"Запорізька область","mykolaiv":"Миколаївська область","odesa":"Одеська область","kherson":"Херсонська область","donetsk":"Донецька область","luhansk":"Луганська область","kharkiv":"Харківська область","crimea":"Автономна Республіка Крим","sevastopol":"м. Севастополь"}},
      short: {"x":{"volyn":"Волинська","zakarpattia":"Закарпатська","ivanofrankivsk":"Івано-Франківська","lviv":"Львівська","rivne":"Рівненська","ternopil":"Тернопільська","khmelnytskyi":"Хмельницька","chernivtsi":"Чернівецька","vinnytsia":"Вінницька","zhytomyr":"Житомирська","kyivoblast":"Київська","kyiv":"м. Київ","kirovohrad":"Кіровоградська","poltava":"Полтавська","sumy":"Сумська","cherkasy":"Черкаська","chernihiv":"Чернігівська","dnipropetrovsk":"Дніпропетровська","zaporizhzhia":"Запорізька","mykolaiv":"Миколаївська","odesa":"Одеська","kherson":"Херсонська","donetsk":"Донецька","luhansk":"Луганська","kharkiv":"Харківська","crimea":"Автономна Республіка Крим","sevastopol":"м. Севастополь"}},
      chip: "{short}",
      chipTitle: {"x":{"volyn":"Volyn","zakarpattia":"Zakarpattia","ivanofrankivsk":"Ivano-Frankivsk","lviv":"Lviv","rivne":"Rivne","ternopil":"Ternopil","khmelnytskyi":"Khmelnytskyi","chernivtsi":"Chernivtsi","vinnytsia":"Vinnytsia","zhytomyr":"Zhytomyr","kyivoblast":"Kyiv Oblast","kyiv":"Kyiv City","kirovohrad":"Kirovohrad","poltava":"Poltava","sumy":"Sumy","cherkasy":"Cherkasy","chernihiv":"Chernihiv","dnipropetrovsk":"Dnipropetrovsk","zaporizhzhia":"Zaporizhzhia","mykolaiv":"Mykolaiv","odesa":"Odesa","kherson":"Kherson","donetsk":"Donetsk","luhansk":"Luhansk","kharkiv":"Kharkiv","crimea":"Crimea","sevastopol":"Sevastopol"}},
      about: {"x":{"volyn":["Volyn","Волинська область","033 · T-03"],"zakarpattia":["Zakarpattia","Закарпатська область","031 · T-07"],"ivanofrankivsk":["Ivano-Frankivsk","Івано-Франківська область","034 · T-09"],"lviv":["Lviv","Львівська область","032 · T-14"],"rivne":["Rivne","Рівненська область","036 · T-18"],"ternopil":["Ternopil","Тернопільська область","035 · T-20"],"khmelnytskyi":["Khmelnytskyi","Хмельницька область","038 · T-23"],"chernivtsi":["Chernivtsi","Чернівецька область","037 · T-26"],"vinnytsia":["Vinnytsia","Вінницька область","043 · T-02"],"zhytomyr":["Zhytomyr","Житомирська область","041 · T-06"],"kyivoblast":["Kyiv Oblast","Київська область","045 · T-10"],"kyiv":["Kyiv City","м. Київ","044 · no T roads"],"kirovohrad":["Kirovohrad","Кіровоградська область","052 · T-12"],"poltava":["Poltava","Полтавська область","053 · T-17"],"sumy":["Sumy","Сумська область","054 · T-19"],"cherkasy":["Cherkasy","Черкаська область","047 · T-24"],"chernihiv":["Chernihiv","Чернігівська область","046 · T-25"],"dnipropetrovsk":["Dnipropetrovsk","Дніпропетровська область","056 · T-04"],"zaporizhzhia":["Zaporizhzhia","Запорізька область","061 · T-08"],"mykolaiv":["Mykolaiv","Миколаївська область","051 · T-15"],"odesa":["Odesa","Одеська область","048 · T-16"],"kherson":["Kherson","Херсонська область","055 · T-22"],"donetsk":["Donetsk","Донецька область","062 · T-05"],"luhansk":["Luhansk","Луганська область","064 · T-13"],"kharkiv":["Kharkiv","Харківська область","057 · T-21"],"crimea":["Crimea","Автономна Республіка Крим","065 · T-01"],"sevastopol":["Sevastopol","м. Севастополь","069 · T-27"]}},
      text: {"t":{"text":"{name}","lang":"uk","cls":"uk"}},
      clicked: "{name} · {chipTitle}",
    },
    {
      key: "roads",
      label: "T-road codes",
      noun: ["code","codes"],
      prompt: "text",
      groups: [["West","",["03","07","09","14","18","20","23","26"]],["Centre","",["02","06","10","12","17","19","24","25"]],["South","",["04","08","15","16","22"]],["East","",["05","13","21"]],["Crimea","",["01","27"]]],
      areas: {"x":{"10":["kyivoblast"],"12":["kirovohrad"],"13":["luhansk"],"14":["lviv"],"15":["mykolaiv"],"16":["odesa"],"17":["poltava"],"18":["rivne"],"19":["sumy"],"20":["ternopil"],"21":["kharkiv"],"22":["kherson"],"23":["khmelnytskyi"],"24":["cherkasy"],"25":["chernihiv"],"26":["chernivtsi"],"27":["sevastopol"],"03":["volyn"],"07":["zakarpattia"],"09":["ivanofrankivsk"],"02":["vinnytsia"],"06":["zhytomyr"],"04":["dnipropetrovsk"],"08":["zaporizhzhia"],"05":["donetsk"],"01":["crimea"]}},
      name: "T-{id}",
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"10":"Kyiv Oblast","12":"Kirovohrad","13":"Luhansk","14":"Lviv","15":"Mykolaiv","16":"Odesa","17":"Poltava","18":"Rivne","19":"Sumy","20":"Ternopil","21":"Kharkiv","22":"Kherson","23":"Khmelnytskyi","24":"Cherkasy","25":"Chernihiv","26":"Chernivtsi","27":"Sevastopol","03":"Volyn","07":"Zakarpattia","09":"Ivano-Frankivsk","02":"Vinnytsia","06":"Zhytomyr","04":"Dnipropetrovsk","08":"Zaporizhzhia","05":"Donetsk","01":"Crimea"}},
      about: {"x":{"10":["Kyiv Oblast","Київська область"],"12":["Kirovohrad","Кіровоградська область"],"13":["Luhansk","Луганська область"],"14":["Lviv","Львівська область"],"15":["Mykolaiv","Миколаївська область"],"16":["Odesa","Одеська область"],"17":["Poltava","Полтавська область"],"18":["Rivne","Рівненська область"],"19":["Sumy","Сумська область"],"20":["Ternopil","Тернопільська область"],"21":["Kharkiv","Харківська область"],"22":["Kherson","Херсонська область"],"23":["Khmelnytskyi","Хмельницька область"],"24":["Cherkasy","Черкаська область"],"25":["Chernihiv","Чернігівська область"],"26":["Chernivtsi","Чернівецька область"],"27":["Sevastopol","м. Севастополь"],"03":["Volyn","Волинська область"],"07":["Zakarpattia","Закарпатська область"],"09":["Ivano-Frankivsk","Івано-Франківська область"],"02":["Vinnytsia","Вінницька область"],"06":["Zhytomyr","Житомирська область"],"04":["Dnipropetrovsk","Дніпропетровська область"],"08":["Zaporizhzhia","Запорізька область"],"05":["Donetsk","Донецька область"],"01":["Crimea","Автономна Республіка Крим"]}},
      text: {"t":{"text":"{name}","cls":"troad"}},
      clicked: {"t":"{name} ({chipTitle})","x":{"kyiv":"Kyiv City: no T roads"}},
    },
  ],
  g: "{a}",
  explore: {"x":{"kherson":{"code":"055","title":"Kherson","sub":["Херсонська область","055 · T-22","South"]},"volyn":{"code":"033","title":"Volyn","sub":["Волинська область","033 · T-03","West"]},"rivne":{"code":"036","title":"Rivne","sub":["Рівненська область","036 · T-18","West"]},"zhytomyr":{"code":"041","title":"Zhytomyr","sub":["Житомирська область","041 · T-06","Centre"]},"kyivoblast":{"code":"045","title":"Kyiv Oblast","sub":["Київська область","045 · T-10","Centre"]},"chernihiv":{"code":"046","title":"Chernihiv","sub":["Чернігівська область","046 · T-25","Centre"]},"sumy":{"code":"054","title":"Sumy","sub":["Сумська область","054 · T-19","Centre"]},"kharkiv":{"code":"057","title":"Kharkiv","sub":["Харківська область","057 · T-21","East"]},"luhansk":{"code":"064","title":"Luhansk","sub":["Луганська область","064 · T-13","East"]},"donetsk":{"code":"062","title":"Donetsk","sub":["Донецька область","062 · T-05","East"]},"zaporizhzhia":{"code":"061","title":"Zaporizhzhia","sub":["Запорізька область","061 · T-08","South"]},"lviv":{"code":"032","title":"Lviv","sub":["Львівська область","032 · T-14","West"]},"ivanofrankivsk":{"code":"034","title":"Ivano-Frankivsk","sub":["Івано-Франківська область","034 · T-09","West"]},"zakarpattia":{"code":"031","title":"Zakarpattia","sub":["Закарпатська область","031 · T-07","West"]},"ternopil":{"code":"035","title":"Ternopil","sub":["Тернопільська область","035 · T-20","West"]},"chernivtsi":{"code":"037","title":"Chernivtsi","sub":["Чернівецька область","037 · T-26","West"]},"odesa":{"code":"048","title":"Odesa","sub":["Одеська область","048 · T-16","South"]},"mykolaiv":{"code":"051","title":"Mykolaiv","sub":["Миколаївська область","051 · T-15","South"]},"crimea":{"code":"065","title":"Crimea","sub":["Автономна Республіка Крим","065 · T-01","Crimea"]},"vinnytsia":{"code":"043","title":"Vinnytsia","sub":["Вінницька область","043 · T-02","Centre"]},"khmelnytskyi":{"code":"038","title":"Khmelnytskyi","sub":["Хмельницька область","038 · T-23","West"]},"cherkasy":{"code":"047","title":"Cherkasy","sub":["Черкаська область","047 · T-24","Centre"]},"poltava":{"code":"053","title":"Poltava","sub":["Полтавська область","053 · T-17","Centre"]},"dnipropetrovsk":{"code":"056","title":"Dnipropetrovsk","sub":["Дніпропетровська область","056 · T-04","South"]},"kirovohrad":{"code":"052","title":"Kirovohrad","sub":["Кіровоградська область","052 · T-12","Centre"]},"kyiv":{"code":"044","title":"Kyiv City","sub":["м. Київ","044 · no T roads","Centre"]},"sevastopol":{"code":"069","title":"Sevastopol","sub":["м. Севастополь","069 · T-27","Crimea"]}}},
};
