// Ecuador Provinces. 24 provinces (dissolved from INEC cantons) in 4 natural
// regions. Galápagos is drawn as an inset closer to the mainland; the street map has it at its real position.

const LAYERS = {
  key: "ecprov",
  borders: ["M21.799999999999997,91.4H296.2V328.2H21.799999999999997Z"],
  size: [1000,682],
  pad: 16,
  maxZoom: 30,
  labelScale: 0.3,
  fly: {"pad":1.6,"min":0.05},
  street: {"bounds":[[-5.1,-81.2],[1.5,-75.1]],"maxBounds":[[-9,-95],[5,-70]]},
  hintLabel: "Color by region",
  exploreKind: "provinces",
  kinds: [
    {
      key: "regions",
      label: "Natural regions",
      noun: ["region","regions"],
      prompt: "name",
      hints: false,
      groups: [["Regions","",["C","S","A","G"]]],
      areas: {"x":{"C":["p07","p08","p09","p12","p13","p24","p23"],"S":["p01","p02","p03","p04","p06","p05","p10","p11","p17","p18"],"A":["p14","p15","p22","p16","p21","p19"],"G":["p20"]}},
      name: {"x":{"C":"Costa","S":"Sierra","A":"Amazonía","G":"Galápagos"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"C":"Coast","S":"Andes","A":"Oriente","G":"Islands"}},
      about: {"x":{"C":["Coast","7 provinces"],"S":["Andes","10 provinces"],"A":["Oriente","6 provinces"],"G":["Islands","1 provinces"]}},
      clicked: "{name} ({@name})",
    },
    {
      key: "provinces",
      label: "Provinces",
      noun: ["province","provinces"],
      prompt: "name",
      groups: [["Costa","Coast",["p07","p08","p09","p12","p13","p24","p23"]],["Sierra","Andes",["p01","p02","p03","p04","p06","p05","p10","p11","p17","p18"]],["Amazonía","Oriente",["p14","p15","p22","p16","p21","p19"]],["Galápagos","Islands",["p20"]]],
      areas: "@id",
      name: "{@name}",
      short: {"t":"{name}","x":{"p23":"Santo Domingo"}},
      chip: "{short}",
      chipTitle: {"x":{"p07":"Machala","p08":"Esmeraldas","p09":"Guayaquil","p12":"Babahoyo","p13":"Portoviejo","p24":"Santa Elena","p23":"Santo Domingo","p01":"Cuenca","p02":"Guaranda","p03":"Azogues","p04":"Tulcán","p06":"Riobamba","p05":"Latacunga","p10":"Ibarra","p11":"Loja","p17":"Quito","p18":"Ambato","p14":"Macas","p15":"Tena","p22":"Puerto Francisco de Orellana","p16":"Puyo","p21":"Nueva Loja","p19":"Zamora","p20":"Puerto Baquerizo Moreno"}},
      detail: ["Show region","{group}"],
      about: {"t":["{group}","Area code 0{@phone}","Capital: {chipTitle}"]},
      clicked: "{name}",
    },
  ],
  g: "{@region}",
  explore: {"t":{"code":"0{@phone}","title":"{@name}","sub":["{regions.name}","{provinces.about1}","{provinces.about2}"]}},
};
