// Russia Area Codes. Each map area is one federal subject (region);
// a region can have several area codes, and code 818 covers two regions.

const LAYERS = {
  key: "rucodes",
  context: false,
  borders: "DATA.fd",
  size: [1400,778],
  pad: 16,
  maxZoom: 45,
  labelScale: 0.3,
  fly: {"pad":1.6,"min":0.03333333333333333},
  street: {"bounds":[[41.2,19.6],[77.7,190]],"maxBounds":[[25,0],[86,215]]},
  hintLabel: "Color by first digit",
  exploreKind: "codes",
  kinds: [
    {
      key: "codes",
      label: "Area codes",
      noun: ["code","codes"],
      prompt: "dial",
      clickAll: true,
      labelPerArea: true,
      groups: [["Central","",["471","472","473","474","475","481","482","483","484","485","486","487","491","492","493","494","495","496","498","499"]],["Northwestern","",["401","811","812","813","814","815","816","817","818","821"]],["Southern","",["844","847","851","861","862","863","877"]],["North Caucasian","",["865","866","867","871","872","873","878","879"]],["Volga","",["341","342","347","353","831","833","834","835","836","841","842","843","845","846","848","855"]],["Ural","",["343","345","346","349","351","352"]],["Siberian","",["381","382","383","384","385","388","390","391","394","395"]],["Far Eastern","",["301","302","411","413","415","416","421","423","424","426","427"]]],
      areas: "@k[]",
      name: "({id})",
      short: "{id}",
      chip: "{id}",
      chipTitle: {"t":"{@n}","x":{"818":"Arkhangelsk Oblast and Nenets Okrug"}},
      detail: ["Show district","{group} Federal District"],
      about: {"t":"{@n}: {@ct}","x":{"818":"Arkhangelsk Oblast: Arkhangelsk, Severodvinsk; Nenets Okrug: Naryan-Mar"}},
      clicked: "{@n} ({@k})",
    },
    {
      key: "digit1",
      label: "First digit",
      noun: ["zone","zones"],
      prompt: "dial",
      hints: false,
      groups: [["Zones","area codes by first digit",["3","4","8"]]],
      areas: {"x":{"3":["BU","ZAB","UD","PER","SVE","TYU","KHM","BA","YAN","CHE","KGN","ORE","OMS","TOM","NVS","KEM","ALT","AL","KK","KYA","TY","IRK"],"4":["KGD","SA","MAG","KAM","AMU","KHA","PRI","SAK","YEV","CHU","KRS","BEL","VOR","LIP","TAM","SMO","TVE","BRY","KLU","YAR","ORL","TUL","RYA","VLA","IVA","KOS","MOW","MOS"],"8":["PSK","SPE","LEN","KR","MUR","NGR","VLG","ARK","NEN","KO","NIZ","KIR","MO","CU","ME","PNZ","ULY","TA","VGG","SAR","SAM","KL","AST","KDA","ROS","STA","KB","SE","CE","DA","IN","AD","KC"]}},
      name: "{id}xx",
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"3":"Buryatia, Zabaykalsky Krai, Udmurtia, Perm Krai, Sverdlovsk Oblast, Tyumen Oblast, Khanty-Mansi Okrug, Bashkortostan, Yamalo-Nenets Okrug, Chelyabinsk Oblast, Kurgan Oblast, Orenburg Oblast, Omsk Oblast, Tomsk Oblast, Novosibirsk Oblast, Kemerovo Oblast, Altai Krai, Altai Republic, Khakassia, Krasnoyarsk Krai, Tuva, Irkutsk Oblast","4":"Kaliningrad Oblast, Sakha (Yakutia), Magadan Oblast, Kamchatka Krai, Amur Oblast, Khabarovsk Krai, Primorsky Krai, Sakhalin Oblast, Jewish Autonomous Oblast, Chukotka, Kursk Oblast, Belgorod Oblast, Voronezh Oblast, Lipetsk Oblast, Tambov Oblast, Smolensk Oblast, Tver Oblast, Bryansk Oblast, Kaluga Oblast, Yaroslavl Oblast, Oryol Oblast, Tula Oblast, Ryazan Oblast, Vladimir Oblast, Ivanovo Oblast, Kostroma Oblast, Moscow, Moscow Oblast","8":"Pskov Oblast, Saint Petersburg, Leningrad Oblast, Karelia, Murmansk Oblast, Novgorod Oblast, Vologda Oblast, Arkhangelsk Oblast, Nenets Okrug, Komi Republic, Nizhny Novgorod Oblast, Kirov Oblast, Mordovia, Chuvashia, Mari El, Penza Oblast, Ulyanovsk Oblast, Tatarstan, Volgograd Oblast, Saratov Oblast, Samara Oblast, Kalmykia, Astrakhan Oblast, Krasnodar Krai, Rostov Oblast, Stavropol Krai, Kabardino-Balkaria, North Ossetia, Chechnya, Dagestan, Ingushetia, Adygea, Karachay-Cherkessia"}},
      about: {"x":{"3":"22 codes in 22 regions","4":"30 codes in 28 regions","8":"36 codes in 33 regions"}},
      clicked: "{name} ({@n})",
    },
    {
      key: "digit2",
      label: "First two digits",
      noun: ["zone","zones"],
      prompt: "dial",
      groups: [["3xx","",["30","34","35","38","39"]],["4xx","",["40","41","42","47","48","49"]],["8xx","",["81","82","83","84","85","86","87"]]],
      areas: {"x":{"30":["BU","ZAB"],"34":["UD","PER","SVE","TYU","KHM","BA","YAN"],"35":["CHE","KGN","ORE"],"38":["OMS","TOM","NVS","KEM","ALT","AL"],"39":["KK","KYA","TY","IRK"],"40":["KGD"],"41":["SA","MAG","KAM","AMU"],"42":["KHA","PRI","SAK","YEV","CHU"],"47":["KRS","BEL","VOR","LIP","TAM"],"48":["SMO","TVE","BRY","KLU","YAR","ORL","TUL"],"49":["RYA","VLA","IVA","KOS","MOW","MOS"],"81":["PSK","SPE","LEN","KR","MUR","NGR","VLG","ARK","NEN"],"82":["KO"],"83":["NIZ","KIR","MO","CU","ME"],"84":["PNZ","ULY","TA","VGG","SAR","SAM","KL"],"85":["AST","TA"],"86":["KDA","ROS","STA","KB","SE"],"87":["CE","DA","IN","AD","KC","STA"]}},
      name: "{id}x",
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"30":"Buryatia, Zabaykalsky Krai","34":"Udmurtia, Perm Krai, Sverdlovsk Oblast, Tyumen Oblast, Khanty-Mansi Okrug, Bashkortostan, Yamalo-Nenets Okrug","35":"Chelyabinsk Oblast, Kurgan Oblast, Orenburg Oblast","38":"Omsk Oblast, Tomsk Oblast, Novosibirsk Oblast, Kemerovo Oblast, Altai Krai, Altai Republic","39":"Khakassia, Krasnoyarsk Krai, Tuva, Irkutsk Oblast","40":"Kaliningrad Oblast","41":"Sakha (Yakutia), Magadan Oblast, Kamchatka Krai, Amur Oblast","42":"Khabarovsk Krai, Primorsky Krai, Sakhalin Oblast, Jewish Autonomous Oblast, Chukotka","47":"Kursk Oblast, Belgorod Oblast, Voronezh Oblast, Lipetsk Oblast, Tambov Oblast","48":"Smolensk Oblast, Tver Oblast, Bryansk Oblast, Kaluga Oblast, Yaroslavl Oblast, Oryol Oblast, Tula Oblast","49":"Ryazan Oblast, Vladimir Oblast, Ivanovo Oblast, Kostroma Oblast, Moscow, Moscow Oblast","81":"Pskov Oblast, Saint Petersburg, Leningrad Oblast, Karelia, Murmansk Oblast, Novgorod Oblast, Vologda Oblast, Arkhangelsk Oblast, Nenets Okrug","82":"Komi Republic","83":"Nizhny Novgorod Oblast, Kirov Oblast, Mordovia, Chuvashia, Mari El","84":"Penza Oblast, Ulyanovsk Oblast, Tatarstan, Volgograd Oblast, Saratov Oblast, Samara Oblast, Kalmykia","85":"Astrakhan Oblast, Tatarstan","86":"Krasnodar Krai, Rostov Oblast, Stavropol Krai, Kabardino-Balkaria, North Ossetia","87":"Chechnya, Dagestan, Ingushetia, Adygea, Karachay-Cherkessia, Stavropol Krai"}},
      about: "{chipTitle}",
      clicked: {"t":"{name} ({@n})","x":{"STA":"86x / 87x (Stavropol Krai)","TA":"84x / 85x (Tatarstan)"}},
    },
    {
      key: "districts",
      label: "Federal districts",
      noun: ["district","districts"],
      prompt: "name",
      groups: [["Federal districts","",["C","NW","S","NC","V","U","SIB","FE"]]],
      areas: "@fd",
      name: {"x":{"C":"Central","NW":"Northwestern","S":"Southern","NC":"North Caucasian","V":"Volga","U":"Ural","SIB":"Siberian","FE":"Far Eastern"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"C":"Belgorod Oblast, Bryansk Oblast, Ivanovo Oblast, Kaluga Oblast, Kostroma Oblast, Kursk Oblast, Lipetsk Oblast, Moscow, Moscow Oblast, Oryol Oblast, Ryazan Oblast, Smolensk Oblast, Tambov Oblast, Tula Oblast, Tver Oblast, Vladimir Oblast, Voronezh Oblast, Yaroslavl Oblast","NW":"Arkhangelsk Oblast, Kaliningrad Oblast, Karelia, Komi Republic, Leningrad Oblast, Murmansk Oblast, Nenets Okrug, Novgorod Oblast, Pskov Oblast, Saint Petersburg, Vologda Oblast","S":"Adygea, Astrakhan Oblast, Kalmykia, Krasnodar Krai, Rostov Oblast, Volgograd Oblast","NC":"Chechnya, Dagestan, Ingushetia, Kabardino-Balkaria, Karachay-Cherkessia, North Ossetia, Stavropol Krai","V":"Bashkortostan, Chuvashia, Kirov Oblast, Mari El, Mordovia, Nizhny Novgorod Oblast, Orenburg Oblast, Penza Oblast, Perm Krai, Samara Oblast, Saratov Oblast, Tatarstan, Udmurtia, Ulyanovsk Oblast","U":"Chelyabinsk Oblast, Khanty-Mansi Okrug, Kurgan Oblast, Sverdlovsk Oblast, Tyumen Oblast, Yamalo-Nenets Okrug","SIB":"Altai Krai, Altai Republic, Irkutsk Oblast, Kemerovo Oblast, Khakassia, Krasnoyarsk Krai, Novosibirsk Oblast, Omsk Oblast, Tomsk Oblast, Tuva","FE":"Amur Oblast, Buryatia, Chukotka, Jewish Autonomous Oblast, Kamchatka Krai, Khabarovsk Krai, Magadan Oblast, Primorsky Krai, Sakha (Yakutia), Sakhalin Oblast, Zabaykalsky Krai"}},
      about: {"x":{"C":"18 regions","NW":"11 regions","S":"6 regions","NC":"7 regions","V":"14 regions","U":"6 regions","SIB":"10 regions","FE":"11 regions"}},
      clicked: "the {name} district ({@n})",
    },
    {
      key: "regions",
      label: "Regions",
      noun: ["region","regions"],
      prompt: "name",
      lang: "English",
      groups: [["Central","",["BEL","BRY","IVA","KLU","KOS","KRS","LIP","MOW","MOS","ORL","RYA","SMO","TAM","TUL","TVE","VLA","VOR","YAR"]],["Northwestern","",["ARK","KGD","KR","KO","LEN","MUR","NEN","NGR","PSK","SPE","VLG"]],["Southern","",["AD","AST","KL","KDA","ROS","VGG"]],["North Caucasian","",["CE","DA","IN","KB","KC","SE","STA"]],["Volga","",["BA","CU","KIR","ME","MO","NIZ","ORE","PNZ","PER","SAM","SAR","TA","UD","ULY"]],["Ural","",["CHE","KHM","KGN","SVE","TYU","YAN"]],["Siberian","",["ALT","AL","IRK","KEM","KK","KYA","NVS","OMS","TOM","TY"]],["Far Eastern","",["AMU","BU","CHU","YEV","KAM","KHA","MAG","PRI","SA","SAK","ZAB"]]],
      areas: "@id",
      name: "{@n}",
      short: "{@n}",
      chip: "{@n}",
      chipTitle: "{@ct}",
      about: {"t":["{@ct}","Area code {@k}"]},
      clicked: "{@n}",
    },
    {
      key: "cyrillic",
      label: "Cyrillic",
      noun: ["region","regions"],
      prompt: "text",
      of: "regions",
      lang: "Russian",
      groups: [["Central","",["BEL","BRY","VLA","VOR","IVA","KLU","KOS","KRS","LIP","MOW","MOS","ORL","RYA","SMO","TAM","TVE","TUL","YAR"]],["Northwestern","",["ARK","VLG","KGD","KR","LEN","MUR","NEN","NGR","PSK","KO","SPE"]],["Southern","",["AD","AST","VGG","KL","KDA","ROS"]],["North Caucasian","",["DA","IN","KB","KC","SE","STA","CE"]],["Volga","",["BA","KIR","ME","MO","NIZ","ORE","PNZ","PER","SAM","SAR","TA","UD","ULY","CU"]],["Ural","",["KGN","SVE","TYU","KHM","CHE","YAN"]],["Siberian","",["ALT","IRK","KEM","KYA","NVS","OMS","AL","TOM","TY","KK"]],["Far Eastern","",["AMU","BU","YEV","ZAB","KAM","MAG","PRI","SAK","KHA","CHU","SA"]]],
      areas: "@id",
      name: {"x":{"BEL":"Белгородская область","BRY":"Брянская область","VLA":"Владимирская область","VOR":"Воронежская область","IVA":"Ивановская область","KLU":"Калужская область","KOS":"Костромская область","KRS":"Курская область","LIP":"Липецкая область","MOW":"Москва","MOS":"Московская область","ORL":"Орловская область","RYA":"Рязанская область","SMO":"Смоленская область","TAM":"Тамбовская область","TVE":"Тверская область","TUL":"Тульская область","YAR":"Ярославская область","ARK":"Архангельская область","VLG":"Вологодская область","KGD":"Калининградская область","KR":"Карелия","LEN":"Ленинградская область","MUR":"Мурманская область","NEN":"Ненецкий автономный округ","NGR":"Новгородская область","PSK":"Псковская область","KO":"Республика Коми","SPE":"Санкт-Петербург","AD":"Адыгея","AST":"Астраханская область","VGG":"Волгоградская область","KL":"Калмыкия","KDA":"Краснодарский край","ROS":"Ростовская область","DA":"Дагестан","IN":"Ингушетия","KB":"Кабардино-Балкария","KC":"Карачаево-Черкесия","SE":"Северная Осетия — Алания","STA":"Ставропольский край","CE":"Чечня","BA":"Башкортостан","KIR":"Кировская область","ME":"Марий Эл","MO":"Мордовия","NIZ":"Нижегородская область","ORE":"Оренбургская область","PNZ":"Пензенская область","PER":"Пермский край","SAM":"Самарская область","SAR":"Саратовская область","TA":"Татарстан","UD":"Удмуртия","ULY":"Ульяновская область","CU":"Чувашия","KGN":"Курганская область","SVE":"Свердловская область","TYU":"Тюменская область","KHM":"Ханты-Мансийский автономный округ — Югра","CHE":"Челябинская область","YAN":"Ямало-Ненецкий автономный округ","ALT":"Алтайский край","IRK":"Иркутская область","KEM":"Кемеровская область","KYA":"Красноярский край","NVS":"Новосибирская область","OMS":"Омская область","AL":"Республика Алтай","TOM":"Томская область","TY":"Тыва","KK":"Хакасия","AMU":"Амурская область","BU":"Бурятия","YEV":"Еврейская автономная область","ZAB":"Забайкальский край","KAM":"Камчатский край","MAG":"Магаданская область","PRI":"Приморский край","SAK":"Сахалинская область","KHA":"Хабаровский край","CHU":"Чукотский автономный округ","SA":"Якутия"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: "{@n}",
      about: {"t":["{@n}","{@ct}"]},
      text: {"t":{"text":"{name}","lang":"ru","cls":"city"}},
      clicked: "{name} · {@n}",
    },
  ],
  g: "{digit1.p}",
  explore: {"t":{"code":"{@k}","title":"{@n}","sub":["{@ct}","{codes.detail}"]}},
};
