// Malaysia on the map of the 13 states and 3 federal territories (data.js, DOSM).
// One config serves three pages (<body data-kinds>): States (states, Jawi names; the regions only group them), Postcodes (state ranges,
// two-digit prefixes) and State Clues (road letters, Jawi signs, bin companies, power companies).
//
// Sources: postcodes: data.gov.my "Postcode" (MCMC, CC BY 4.0), every 2-digit prefix with its state; 34950 Bandar
// Baharu (Kedah) is the only code under another state's prefix. Road letters: Malaysian state roads system (JKR,
// via Wikipedia). Jawi on signs: mandated in Kelantan, Terengganu and Pahang (Wikipedia, Jawi script). Bins: the
// three Act 672 concessionaires (KPKT/JPSPN: Alam Flora, SWM Environment, E-Idaman) and KDEB Waste Management
// (Selangor state). Power: TNB (Peninsula), SESB (Sabah, Labuan), Sarawak Energy. Jawi names: Wikidata (CC0).
// Regions: Peninsular Malaysia's informal regions (Wikipedia, Peninsular Malaysia) plus East Malaysia.

const LAYERS = {
  key: "mystates",
  size: [1000,336],
  pad: 16,
  maxZoom: 40,
  labelScale: 0.3,
  fly: {"pad":1.6,"min":0.0375},
  street: {"bounds":[[0.8,99.6],[7.4,119.3]],"maxBounds":[[-6,90],[14,128]]},
  hintLabel: "Color each state",
  exploreKind: "states",
  d: {"KUL":"M96.8,214.8a5.5,5.5 0 1,0 11,0a5.5,5.5 0 1,0 -11,0z","PJY":"M98.2,226.6a4.5,4.5 0 1,0 9,0a4.5,4.5 0 1,0 -9,0z"},
  top: ["KUL","PJY"],
  kinds: [
    {
      key: "regions",
      label: "Regions",
      groupsOnly: true,
      noun: ["region","regions"],
      prompt: "name",
      hints: false,
      groups: [["Regions","informal",["North","Central","South","East Coast","East Malaysia"]]],
      areas: {"x":{"North":["PLS","KDH","PNG","PRK"],"Central":["SGR","KUL","PJY"],"South":["NSN","MLK","JHR"],"East Coast":["KTN","TRG","PHG"],"East Malaysia":["SBH","SWK","LBN"]}},
      name: "{id}",
      short: "{id}",
      chip: "{id}",
      chipTitle: {"x":{"North":"Kedah, Penang, Perak, Perlis","Central":"Kuala Lumpur, Putrajaya, Selangor","South":"Johor, Melaka, Negeri Sembilan","East Coast":"Kelantan, Pahang, Terengganu","East Malaysia":"Labuan, Sabah, Sarawak"}},
      about: "{chipTitle}",
      clicked: {"x":{"SGR":"Selangor · Central","PHG":"Pahang · East Coast","PNG":"Penang · North","SWK":"Sarawak · East Malaysia","KDH":"Kedah · North","PRK":"Perak · North","SBH":"Sabah · East Malaysia","KTN":"Kelantan · East Coast","NSN":"Negeri Sembilan · South","KUL":"Kuala Lumpur · Central","LBN":"Labuan · East Malaysia","PLS":"Perlis · North","JHR":"Johor · South","MLK":"Melaka · South","TRG":"Terengganu · East Coast","PJY":"Putrajaya · Central"}},
    },
    {
      key: "states",
      label: "States",
      noun: ["state","states"],
      prompt: "name",
      lang: "English",
      groups: [["North","",["KDH","PNG","PRK","PLS"]],["Central","",["KUL","PJY","SGR"]],["South","",["JHR","MLK","NSN"]],["East Coast","",["KTN","PHG","TRG"]],["East Malaysia","",["LBN","SBH","SWK"]]],
      areas: "@id",
      name: {"x":{"KDH":"Kedah","PNG":"Penang (Pulau Pinang)","PRK":"Perak","PLS":"Perlis","KUL":"Kuala Lumpur","PJY":"Putrajaya","SGR":"Selangor","JHR":"Johor","MLK":"Melaka","NSN":"Negeri Sembilan","KTN":"Kelantan","PHG":"Pahang","TRG":"Terengganu","LBN":"Labuan","SBH":"Sabah","SWK":"Sarawak"}},
      short: {"t":"{name}","x":{"PNG":"Penang"}},
      chip: "{short}",
      chipTitle: {"t":"State · {group}","x":{"KUL":"Federal territory · Central","PJY":"Federal territory · Central","LBN":"Federal territory · East Malaysia"}},
      about: {"x":{"KDH":["State · North","Postcodes 05–09","State roads K","Power TNB","Bins E-Idaman"],"PNG":["State · North","Postcodes 10–14","State roads P","Power TNB"],"PRK":["State · North","Postcodes 30–36","State roads A","Power TNB"],"PLS":["State · North","Postcodes 01–02","State roads R","Power TNB","Bins E-Idaman"],"KUL":["Federal territory · Central","Postcodes 50–60","No state roads","Power TNB","Bins Alam Flora"],"PJY":["Federal territory · Central","Postcodes 62","No state roads","Power TNB","Bins Alam Flora"],"SGR":["State · Central","Postcodes 40–48 · 63–64 · 68","State roads B","Power TNB","Bins KDEB Waste Management"],"JHR":["State · South","Postcodes 79–86","State roads J","Power TNB","Bins SWM Environment"],"MLK":["State · South","Postcodes 75–78","State roads M","Power TNB","Bins SWM Environment"],"NSN":["State · South","Postcodes 70–73","State roads N","Power TNB","Bins SWM Environment"],"KTN":["State · East Coast","Postcodes 15–18","State roads D","Power TNB"],"PHG":["State · East Coast","Postcodes 25–28 · 39 · 49 · 69","State roads C","Power TNB","Bins Alam Flora"],"TRG":["State · East Coast","Postcodes 20–24","State roads T","Power TNB"],"LBN":["Federal territory · East Malaysia","Postcodes 87","No state roads","Power SESB"],"SBH":["State · East Malaysia","Postcodes 88–91","State roads SA","Power SESB"],"SWK":["State · East Malaysia","Postcodes 93–98","State roads Q","Power Sarawak Energy"]}},
      clicked: "{name}",
    },
    {
      key: "jawi",
      label: "Jawi names",
      noun: ["name","names"],
      prompt: "text",
      of: "states",
      lang: "Jawi",
      groups: [["North","",["KDH","PNG","PRK","PLS"]],["Central","",["KUL","PJY","SGR"]],["South","",["JHR","MLK","NSN"]],["East Coast","",["KTN","PHG","TRG"]],["East Malaysia","",["LBN","SBH","SWK"]]],
      areas: "@id",
      name: {"x":{"KDH":"قدح · Kedah","PNG":"ڤولاو ڤينڠ · Penang","PRK":"ڤيراق · Perak","PLS":"ڤرليس · Perlis","KUL":"کوالا لمڤور · Kuala Lumpur","PJY":"ڤوتراجاي · Putrajaya","SGR":"سلاڠور · Selangor","JHR":"جوهر · Johor","MLK":"ملاک · Melaka","NSN":"نݢري سمبيلن · Negeri Sembilan","KTN":"کلنتن · Kelantan","PHG":"ڤهڠ · Pahang","TRG":"ترڠݢانو · Terengganu","LBN":"لابوان · Labuan","SBH":"سابه · Sabah","SWK":"سراوق · Sarawak"}},
      short: {"x":{"KDH":"قدح","PNG":"ڤولاو ڤينڠ","PRK":"ڤيراق","PLS":"ڤرليس","KUL":"کوالا لمڤور","PJY":"ڤوتراجاي","SGR":"سلاڠور","JHR":"جوهر","MLK":"ملاک","NSN":"نݢري سمبيلن","KTN":"کلنتن","PHG":"ڤهڠ","TRG":"ترڠݢانو","LBN":"لابوان","SBH":"سابه","SWK":"سراوق"}},
      chip: "{short}",
      chipTitle: {"x":{"KDH":"Kedah","PNG":"Penang","PRK":"Perak","PLS":"Perlis","KUL":"Kuala Lumpur","PJY":"Putrajaya","SGR":"Selangor","JHR":"Johor","MLK":"Melaka","NSN":"Negeri Sembilan","KTN":"Kelantan","PHG":"Pahang","TRG":"Terengganu","LBN":"Labuan","SBH":"Sabah","SWK":"Sarawak"}},
      about: {"t":["{chipTitle}","State · {group}"],"x":{"PNG":["Penang (Pulau Pinang)","State · North"],"KUL":["Kuala Lumpur","Federal territory · Central"],"PJY":["Putrajaya","Federal territory · Central"],"LBN":["Labuan","Federal territory · East Malaysia"]}},
      text: {"t":{"text":"{chip}","lang":"ms-Arab","cls":"jawi"}},
      clicked: "{name}",
    },
    {
      key: "postranges",
      label: "Postcode ranges",
      noun: ["range","ranges"],
      prompt: "name",
      groups: [["North","",["KDH","PNG","PRK","PLS"]],["Central","",["KUL","PJY","SGR"]],["South","",["JHR","MLK","NSN"]],["East Coast","",["KTN","PHG","TRG"]],["East Malaysia","",["LBN","SBH","SWK"]]],
      areas: "@id",
      name: {"x":{"KDH":"05–09","PNG":"10–14","PRK":"30–36","PLS":"01–02","KUL":"50–60","PJY":"62","SGR":"40–48 · 63–64 · 68","JHR":"79–86","MLK":"75–78","NSN":"70–73","KTN":"15–18","PHG":"25–28 · 39 · 49 · 69","TRG":"20–24","LBN":"87","SBH":"88–91","SWK":"93–98"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"KDH":"Kedah","PNG":"Penang","PRK":"Perak","PLS":"Perlis","KUL":"Kuala Lumpur","PJY":"Putrajaya","SGR":"Selangor","JHR":"Johor","MLK":"Melaka","NSN":"Negeri Sembilan","KTN":"Kelantan","PHG":"Pahang","TRG":"Terengganu","LBN":"Labuan","SBH":"Sabah","SWK":"Sarawak"}},
      about: {"x":{"KDH":["Kedah","05 Alor Setar · 06 Jitra, Pendang · 07 Langkawi · 08 Sungai Petani, Gurun · 09 Kulim, Baling"],"PNG":["Penang (Pulau Pinang)","10 George Town · 11 Bayan Lepas, Balik Pulau · 12 Butterworth · 13 Butterworth, Kepala Batas · 14 Bukit Mertajam, Nibong Tebal"],"PRK":["Perak","30 Ipoh · 31 Ipoh, Kampar · 32 Sitiawan, Lumut · 33 Kuala Kangsar, Gerik · 34 Taiping, Bagan Serai · 34950 Bandar Baharu, Kedah · 35 Tapah, Tanjung Malim · 36 Teluk Intan"],"PLS":["Perlis","01 Kangar · 02 Arau, Simpang Ampat"],"KUL":["Kuala Lumpur","50 Kuala Lumpur · 51 Kuala Lumpur · 52 Kuala Lumpur · 53 Kuala Lumpur · 54 Kuala Lumpur · 55 Kuala Lumpur · 56 Kuala Lumpur · 57 Kuala Lumpur · 58 Kuala Lumpur · 59 Kuala Lumpur · 60 Kuala Lumpur"],"PJY":["Putrajaya","62 Putrajaya"],"SGR":["Selangor","40 Shah Alam · 41 Klang · 42 Port Klang, Jenjarom · 43 Kajang, Bangi · 44 Kuala Kubu Bharu · 45 Sabak Bernam, Tanjong Karang · 46 Petaling Jaya · 47 Puchong, Subang Jaya · 48 Rawang · 63 Cyberjaya · 64 KLIA · 68 Ampang, Batu Caves"],"JHR":["Johor","79 Iskandar Puteri · 80 Johor Bahru · 81 Johor Bahru, Kulai, Skudai · 82 Pontian · 83 Batu Pahat, Yong Peng · 84 Muar, Tangkak · 85 Segamat · 86 Kluang, Mersing"],"MLK":["Melaka","75 Melaka · 76 Durian Tunggal · 77 Jasin, Merlimau · 78 Alor Gajah, Masjid Tanah"],"NSN":["Negeri Sembilan","70 Seremban · 71 Port Dickson, Rembau · 72 Kuala Pilah, Bahau · 73 Tampin, Gemencheh"],"KTN":["Kelantan","15 Kota Bharu · 16 Bachok, Tumpat · 17 Pasir Mas, Tanah Merah · 18 Kuala Krai, Gua Musang"],"PHG":["Pahang","25 Kuantan · 26 Kuantan, Pekan · 27 Jerantut, Raub, Kuala Lipis · 28 Temerloh, Karak · 39 Cameron Highlands · 49 Bukit Fraser · 69 Genting Highlands"],"TRG":["Terengganu","20 Kuala Terengganu · 21 Kuala Terengganu, Marang · 22 Jerteh, Kuala Besut · 23 Dungun, Paka · 24 Kemaman, Kerteh"],"LBN":["Labuan","87 Labuan"],"SBH":["Sabah","88 Kota Kinabalu · 89 Ranau, Kota Marudu, Papar · 90 Sandakan, Beluran · 91 Tawau, Lahad Datu"],"SWK":["Sarawak","93 Kuching · 94 Bau, Lundu, Serian · 95 Sri Aman, Betong, Saratok · 96 Sibu, Sarikei, Kapit · 97 Bintulu, Tatau · 98 Miri, Limbang"]}},
      clicked: "{chipTitle}: {name}",
    },
    {
      key: "post2",
      label: "Two-digit prefixes",
      noun: ["prefix","prefixes"],
      prompt: "dial",
      groups: [["North","",["10","11","12","13","14","30","31","32","33","34","35","36","01","02","05","06","07","08","09"]],["Central","",["40","41","42","43","44","45","46","47","48","50","51","52","53","54","55","56","57","58","59","60","62","63","64","68"]],["South","",["70","71","72","73","75","76","77","78","79","80","81","82","83","84","85","86"]],["East Coast","",["15","16","17","18","20","21","22","23","24","25","26","27","28","39","49","69"]],["East Malaysia","",["87","88","89","90","91","93","94","95","96","97","98"]]],
      areas: {"x":{"10":["PNG"],"11":["PNG"],"12":["PNG"],"13":["PNG"],"14":["PNG"],"15":["KTN"],"16":["KTN"],"17":["KTN"],"18":["KTN"],"20":["TRG"],"21":["TRG"],"22":["TRG"],"23":["TRG"],"24":["TRG"],"25":["PHG"],"26":["PHG"],"27":["PHG"],"28":["PHG"],"30":["PRK"],"31":["PRK"],"32":["PRK"],"33":["PRK"],"34":["PRK"],"35":["PRK"],"36":["PRK"],"39":["PHG"],"40":["SGR"],"41":["SGR"],"42":["SGR"],"43":["SGR"],"44":["SGR"],"45":["SGR"],"46":["SGR"],"47":["SGR"],"48":["SGR"],"49":["PHG"],"50":["KUL"],"51":["KUL"],"52":["KUL"],"53":["KUL"],"54":["KUL"],"55":["KUL"],"56":["KUL"],"57":["KUL"],"58":["KUL"],"59":["KUL"],"60":["KUL"],"62":["PJY"],"63":["SGR"],"64":["SGR"],"68":["SGR"],"69":["PHG"],"70":["NSN"],"71":["NSN"],"72":["NSN"],"73":["NSN"],"75":["MLK"],"76":["MLK"],"77":["MLK"],"78":["MLK"],"79":["JHR"],"80":["JHR"],"81":["JHR"],"82":["JHR"],"83":["JHR"],"84":["JHR"],"85":["JHR"],"86":["JHR"],"87":["LBN"],"88":["SBH"],"89":["SBH"],"90":["SBH"],"91":["SBH"],"93":["SWK"],"94":["SWK"],"95":["SWK"],"96":["SWK"],"97":["SWK"],"98":["SWK"],"01":["PLS"],"02":["PLS"],"05":["KDH"],"06":["KDH"],"07":["KDH"],"08":["KDH"],"09":["KDH"]}},
      name: "{id}xxx",
      short: "{id}",
      chip: "{name}",
      chipTitle: {"x":{"10":"Penang · George Town","11":"Penang · Bayan Lepas, Balik Pulau","12":"Penang · Butterworth","13":"Penang · Butterworth, Kepala Batas","14":"Penang · Bukit Mertajam, Nibong Tebal","15":"Kelantan · Kota Bharu","16":"Kelantan · Bachok, Tumpat","17":"Kelantan · Pasir Mas, Tanah Merah","18":"Kelantan · Kuala Krai, Gua Musang","20":"Terengganu · Kuala Terengganu","21":"Terengganu · Kuala Terengganu, Marang","22":"Terengganu · Jerteh, Kuala Besut","23":"Terengganu · Dungun, Paka","24":"Terengganu · Kemaman, Kerteh","25":"Pahang · Kuantan","26":"Pahang · Kuantan, Pekan","27":"Pahang · Jerantut, Raub, Kuala Lipis","28":"Pahang · Temerloh, Karak","30":"Perak · Ipoh","31":"Perak · Ipoh, Kampar","32":"Perak · Sitiawan, Lumut","33":"Perak · Kuala Kangsar, Gerik","34":"Perak · Taiping, Bagan Serai · 34950 Bandar Baharu, Kedah","35":"Perak · Tapah, Tanjung Malim","36":"Perak · Teluk Intan","39":"Pahang · Cameron Highlands","40":"Selangor · Shah Alam","41":"Selangor · Klang","42":"Selangor · Port Klang, Jenjarom","43":"Selangor · Kajang, Bangi","44":"Selangor · Kuala Kubu Bharu","45":"Selangor · Sabak Bernam, Tanjong Karang","46":"Selangor · Petaling Jaya","47":"Selangor · Puchong, Subang Jaya","48":"Selangor · Rawang","49":"Pahang · Bukit Fraser","50":"Kuala Lumpur · Kuala Lumpur","51":"Kuala Lumpur · Kuala Lumpur","52":"Kuala Lumpur · Kuala Lumpur","53":"Kuala Lumpur · Kuala Lumpur","54":"Kuala Lumpur · Kuala Lumpur","55":"Kuala Lumpur · Kuala Lumpur","56":"Kuala Lumpur · Kuala Lumpur","57":"Kuala Lumpur · Kuala Lumpur","58":"Kuala Lumpur · Kuala Lumpur","59":"Kuala Lumpur · Kuala Lumpur","60":"Kuala Lumpur · Kuala Lumpur","62":"Putrajaya · Putrajaya","63":"Selangor · Cyberjaya","64":"Selangor · KLIA","68":"Selangor · Ampang, Batu Caves","69":"Pahang · Genting Highlands","70":"Negeri Sembilan · Seremban","71":"Negeri Sembilan · Port Dickson, Rembau","72":"Negeri Sembilan · Kuala Pilah, Bahau","73":"Negeri Sembilan · Tampin, Gemencheh","75":"Melaka · Melaka","76":"Melaka · Durian Tunggal","77":"Melaka · Jasin, Merlimau","78":"Melaka · Alor Gajah, Masjid Tanah","79":"Johor · Iskandar Puteri","80":"Johor · Johor Bahru","81":"Johor · Johor Bahru, Kulai, Skudai","82":"Johor · Pontian","83":"Johor · Batu Pahat, Yong Peng","84":"Johor · Muar, Tangkak","85":"Johor · Segamat","86":"Johor · Kluang, Mersing","87":"Labuan · Labuan","88":"Sabah · Kota Kinabalu","89":"Sabah · Ranau, Kota Marudu, Papar","90":"Sabah · Sandakan, Beluran","91":"Sabah · Tawau, Lahad Datu","93":"Sarawak · Kuching","94":"Sarawak · Bau, Lundu, Serian","95":"Sarawak · Sri Aman, Betong, Saratok","96":"Sarawak · Sibu, Sarikei, Kapit","97":"Sarawak · Bintulu, Tatau","98":"Sarawak · Miri, Limbang","01":"Perlis · Kangar","02":"Perlis · Arau, Simpang Ampat","05":"Kedah · Alor Setar","06":"Kedah · Jitra, Pendang","07":"Kedah · Langkawi","08":"Kedah · Sungai Petani, Gurun","09":"Kedah · Kulim, Baling"}},
      about: {"x":{"10":["Penang (Pulau Pinang)","George Town"],"11":["Penang (Pulau Pinang)","Bayan Lepas, Balik Pulau"],"12":["Penang (Pulau Pinang)","Butterworth"],"13":["Penang (Pulau Pinang)","Butterworth, Kepala Batas"],"14":["Penang (Pulau Pinang)","Bukit Mertajam, Nibong Tebal"],"15":["Kelantan","Kota Bharu"],"16":["Kelantan","Bachok, Tumpat"],"17":["Kelantan","Pasir Mas, Tanah Merah"],"18":["Kelantan","Kuala Krai, Gua Musang"],"20":["Terengganu","Kuala Terengganu"],"21":["Terengganu","Kuala Terengganu, Marang"],"22":["Terengganu","Jerteh, Kuala Besut"],"23":["Terengganu","Dungun, Paka"],"24":["Terengganu","Kemaman, Kerteh"],"25":["Pahang","Kuantan"],"26":["Pahang","Kuantan, Pekan"],"27":["Pahang","Jerantut, Raub, Kuala Lipis"],"28":["Pahang","Temerloh, Karak"],"30":["Perak","Ipoh"],"31":["Perak","Ipoh, Kampar"],"32":["Perak","Sitiawan, Lumut"],"33":["Perak","Kuala Kangsar, Gerik"],"34":["Perak","Taiping, Bagan Serai · 34950 Bandar Baharu, Kedah"],"35":["Perak","Tapah, Tanjung Malim"],"36":["Perak","Teluk Intan"],"39":["Pahang","Cameron Highlands"],"40":["Selangor","Shah Alam"],"41":["Selangor","Klang"],"42":["Selangor","Port Klang, Jenjarom"],"43":["Selangor","Kajang, Bangi"],"44":["Selangor","Kuala Kubu Bharu"],"45":["Selangor","Sabak Bernam, Tanjong Karang"],"46":["Selangor","Petaling Jaya"],"47":["Selangor","Puchong, Subang Jaya"],"48":["Selangor","Rawang"],"49":["Pahang","Bukit Fraser"],"50":["Kuala Lumpur","Kuala Lumpur"],"51":["Kuala Lumpur","Kuala Lumpur"],"52":["Kuala Lumpur","Kuala Lumpur"],"53":["Kuala Lumpur","Kuala Lumpur"],"54":["Kuala Lumpur","Kuala Lumpur"],"55":["Kuala Lumpur","Kuala Lumpur"],"56":["Kuala Lumpur","Kuala Lumpur"],"57":["Kuala Lumpur","Kuala Lumpur"],"58":["Kuala Lumpur","Kuala Lumpur"],"59":["Kuala Lumpur","Kuala Lumpur"],"60":["Kuala Lumpur","Kuala Lumpur"],"62":["Putrajaya","Putrajaya"],"63":["Selangor","Cyberjaya"],"64":["Selangor","KLIA"],"68":["Selangor","Ampang, Batu Caves"],"69":["Pahang","Genting Highlands"],"70":["Negeri Sembilan","Seremban"],"71":["Negeri Sembilan","Port Dickson, Rembau"],"72":["Negeri Sembilan","Kuala Pilah, Bahau"],"73":["Negeri Sembilan","Tampin, Gemencheh"],"75":["Melaka","Melaka"],"76":["Melaka","Durian Tunggal"],"77":["Melaka","Jasin, Merlimau"],"78":["Melaka","Alor Gajah, Masjid Tanah"],"79":["Johor","Iskandar Puteri"],"80":["Johor","Johor Bahru"],"81":["Johor","Johor Bahru, Kulai, Skudai"],"82":["Johor","Pontian"],"83":["Johor","Batu Pahat, Yong Peng"],"84":["Johor","Muar, Tangkak"],"85":["Johor","Segamat"],"86":["Johor","Kluang, Mersing"],"87":["Labuan","Labuan"],"88":["Sabah","Kota Kinabalu"],"89":["Sabah","Ranau, Kota Marudu, Papar"],"90":["Sabah","Sandakan, Beluran"],"91":["Sabah","Tawau, Lahad Datu"],"93":["Sarawak","Kuching"],"94":["Sarawak","Bau, Lundu, Serian"],"95":["Sarawak","Sri Aman, Betong, Saratok"],"96":["Sarawak","Sibu, Sarikei, Kapit"],"97":["Sarawak","Bintulu, Tatau"],"98":["Sarawak","Miri, Limbang"],"01":["Perlis","Kangar"],"02":["Perlis","Arau, Simpang Ampat"],"05":["Kedah","Alor Setar"],"06":["Kedah","Jitra, Pendang"],"07":["Kedah","Langkawi"],"08":["Kedah","Sungai Petani, Gurun"],"09":["Kedah","Kulim, Baling"]}},
      dial: {"t":[["{id}","hot"],["xxx","cold"]]},
      clicked: {"x":{"SGR":"Selangor: 40–48 · 63–64 · 68","PHG":"Pahang: 25–28 · 39 · 49 · 69","PNG":"Penang: 10–14","SWK":"Sarawak: 93–98","KDH":"Kedah: 05–09","PRK":"Perak: 30–36","SBH":"Sabah: 88–91","KTN":"Kelantan: 15–18","NSN":"Negeri Sembilan: 70–73","KUL":"Kuala Lumpur: 50–60","LBN":"Labuan: 87","PLS":"Perlis: 01–02","JHR":"Johor: 79–86","MLK":"Melaka: 75–78","TRG":"Terengganu: 20–24","PJY":"Putrajaya: 62"}},
    },
    {
      key: "roads",
      label: "Road letters",
      noun: ["letter","letters"],
      prompt: "dial",
      groups: [["North","",["KDH","PNG","PRK","PLS"]],["Central","",["SGR"]],["South","",["JHR","MLK","NSN"]],["East Coast","",["KTN","PHG","TRG"]],["East Malaysia","",["SBH","SWK"]]],
      areas: "@id",
      name: {"x":{"KDH":"K","PNG":"P","PRK":"A","PLS":"R","SGR":"B","JHR":"J","MLK":"M","NSN":"N","KTN":"D","PHG":"C","TRG":"T","SBH":"SA","SWK":"Q"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"KDH":"Kedah","PNG":"Penang","PRK":"Perak","PLS":"Perlis","SGR":"Selangor","JHR":"Johor","MLK":"Melaka","NSN":"Negeri Sembilan","KTN":"Kelantan","PHG":"Pahang","TRG":"Terengganu","SBH":"Sabah","SWK":"Sarawak"}},
      about: {"t":["{chipTitle}","State roads {name}1, {name}2, …"],"x":{"PNG":["Penang (Pulau Pinang)","State roads P1, P2, …"]}},
      dial: {"t":[["{name}","hot"]]},
      clicked: {"t":"{name} · {chipTitle}","x":{"KUL":"Kuala Lumpur: federal roads only","LBN":"Labuan: federal roads only","PJY":"Putrajaya: federal roads only"}},
    },
    {
      key: "jawisigns",
      label: "Jawi on signs",
      noun: ["clue","clues"],
      prompt: "name",
      hints: false,
      clickAll: true,
      groups: [["Jawi","",["jawi"]]],
      areas: {"x":{"jawi":["KTN","TRG","PHG"]}},
      name: "Jawi on all signs",
      short: "Jawi",
      chip: "Jawi",
      chipTitle: "Kelantan, Pahang, Terengganu",
      about: "Kelantan, Pahang, Terengganu",
      clicked: {"x":{"SGR":"Selangor","PHG":"Pahang","PNG":"Penang","SWK":"Sarawak","KDH":"Kedah","PRK":"Perak","SBH":"Sabah","KTN":"Kelantan","NSN":"Negeri Sembilan","KUL":"Kuala Lumpur","LBN":"Labuan","PLS":"Perlis","JHR":"Johor","MLK":"Melaka","TRG":"Terengganu","PJY":"Putrajaya"}},
    },
    {
      key: "bins",
      label: "Bin companies",
      noun: ["company","companies"],
      prompt: "name",
      hints: false,
      groups: [["Waste collection","",["af","swm","eid","kdeb"]]],
      areas: {"x":{"af":["KUL","PJY","PHG"],"swm":["NSN","MLK","JHR"],"eid":["PLS","KDH"],"kdeb":["SGR"]}},
      name: {"x":{"af":"Alam Flora","swm":"SWM Environment","eid":"E-Idaman","kdeb":"KDEB Waste Management"}},
      short: "{name}",
      chip: "{name}",
      chipTitle: {"x":{"af":"Kuala Lumpur, Pahang, Putrajaya","swm":"Johor, Melaka, Negeri Sembilan","eid":"Kedah, Perlis","kdeb":"Selangor"}},
      about: "{chipTitle}",
      clicked: {"x":{"SGR":"Selangor: KDEB Waste Management","PHG":"Pahang: Alam Flora","PNG":"Penang","SWK":"Sarawak","KDH":"Kedah: E-Idaman","PRK":"Perak","SBH":"Sabah","KTN":"Kelantan","NSN":"Negeri Sembilan: SWM Environment","KUL":"Kuala Lumpur: Alam Flora","LBN":"Labuan","PLS":"Perlis: E-Idaman","JHR":"Johor: SWM Environment","MLK":"Melaka: SWM Environment","TRG":"Terengganu","PJY":"Putrajaya: Alam Flora"}},
    },
    {
      key: "power",
      label: "Power companies",
      noun: ["company","companies"],
      prompt: "name",
      hints: false,
      groups: [["Electricity","",["tnb","sesb","seb"]]],
      areas: {"x":{"tnb":["PLS","KDH","PNG","PRK","SGR","KUL","PJY","NSN","MLK","JHR","KTN","TRG","PHG"],"sesb":["SBH","LBN"],"seb":["SWK"]}},
      name: {"x":{"tnb":"TNB · Tenaga Nasional","sesb":"SESB · Sabah Electricity","seb":"Sarawak Energy"}},
      short: {"x":{"tnb":"TNB","sesb":"SESB","seb":"Sarawak Energy"}},
      chip: "{short}",
      chipTitle: {"x":{"tnb":"Johor, Kedah, Kelantan, Kuala Lumpur, Melaka, Negeri Sembilan, Pahang, Penang, Perak, Perlis, Putrajaya, Selangor, Terengganu","sesb":"Labuan, Sabah","seb":"Sarawak"}},
      about: "{chipTitle}",
      clicked: {"x":{"SGR":"Selangor: TNB","PHG":"Pahang: TNB","PNG":"Penang: TNB","SWK":"Sarawak: Sarawak Energy","KDH":"Kedah: TNB","PRK":"Perak: TNB","SBH":"Sabah: SESB","KTN":"Kelantan: TNB","NSN":"Negeri Sembilan: TNB","KUL":"Kuala Lumpur: TNB","LBN":"Labuan: SESB","PLS":"Perlis: TNB","JHR":"Johor: TNB","MLK":"Melaka: TNB","TRG":"Terengganu: TNB","PJY":"Putrajaya: TNB"}},
    },
  ],
  g: "{a}",
  explore: {"t":{"code":"{@iso}","title":"{states.name}","sub":["{jawi.about1}","{states.about1}","{states.about2}","Power TNB","{states.about4}"]},"x":{"PNG":{"code":"MY-07","title":"Penang (Pulau Pinang)","sub":["State · North","Postcodes 10–14","State roads P","Power TNB"]},"SWK":{"code":"MY-13","title":"Sarawak","sub":["State · East Malaysia","Postcodes 93–98","State roads Q","Power Sarawak Energy"]},"PRK":{"code":"MY-08","title":"Perak","sub":["State · North","Postcodes 30–36","State roads A","Power TNB"]},"SBH":{"code":"MY-12","title":"Sabah","sub":["State · East Malaysia","Postcodes 88–91","State roads SA","Power SESB"]},"KTN":{"code":"MY-03","title":"Kelantan","sub":["State · East Coast","Postcodes 15–18","State roads D","Power TNB"]},"LBN":{"code":"MY-15","title":"Labuan","sub":["Federal territory · East Malaysia","Postcodes 87","No state roads","Power SESB"]},"TRG":{"code":"MY-11","title":"Terengganu","sub":["State · East Coast","Postcodes 20–24","State roads T","Power TNB"]}}},
};
