#!/usr/bin/env node
// geo2quiz: boundary polygons (GeoJSON, WGS84) -> the map files of an area quiz.
//
//   node tools/geo2quiz.mjs --in areas.geojson --out quizzes/<folder> --iso3 THA [--width 1000] [--props name,code]
//        [--min-area 1.5] [--base] [--note "Borders: geoBoundaries (CC BY 4.0)"]
//
// Every feature needs a unique properties.id. Writes:
//   <out>/data.js  const DATA = { w, h, kpu, proj, reg: [{ id, d, lx, ly, a, ...props }], ctx, land, lines }
//                  reg: one entry per area (SVG path in map units, label point, size); ctx: neighbouring land
//                  (Natural Earth); land/lines (with --base): the country and its inner borders; proj: the projection,
//                  so cities and pins can be placed in the same map space (tools/lib/geo.mjs projectionFrom)
//   <out>/geo.js   const GEO = { [id]: { rings: [[[lat, lng]…]…], lab: [lat, lng] } } for the street map
import fs from 'node:fs';
import path from 'node:path';
import { parseArgs } from 'node:util';
import { readGeoJSON, fitProjection, planarFeatures, labelAndArea, geoRings, contextPath, landAndLines, kmPerUnit, svgPath } from './lib/geo.mjs';

const { values: o } = parseArgs({
  options: {
    in: { type: 'string' }, out: { type: 'string' }, iso3: { type: 'string' },
    width: { type: 'string', default: '1000' }, pad: { type: 'string', default: '0' },
    props: { type: 'string', default: '' }, 'min-area': { type: 'string', default: '1.5' }, base: { type: 'boolean', default: false },
    note: { type: 'string', default: '' }, 'no-context': { type: 'boolean', default: false },
    'data-var': { type: 'string', default: 'DATA' }, 'geo-var': { type: 'string', default: 'GEO' },
    'data-file': { type: 'string', default: 'data.js' }, 'geo-file': { type: 'string', default: 'geo.js' },
  },
});
if (!o.in || !o.out || !o.iso3) { console.error('usage: geo2quiz --in areas.geojson --out quizzes/<folder> --iso3 XXX'); process.exit(1); }

const fc = readGeoJSON(o.in);
const ids = fc.features.map(f => f.properties?.id);
if (ids.some(id => id === undefined || id === null)) throw new Error('every feature needs properties.id');
if (new Set(ids.map(String)).size !== ids.length) throw new Error('feature ids must be unique');

const width = +o.width;
const { proj, w, h, def } = fitProjection(fc, width, +o.pad);
const { topo, features } = planarFeatures(fc, proj, { minArea: +o['min-area'] });
const props = o.props ? o.props.split(',').map(s => s.trim()).filter(Boolean) : [];

const reg = [], GEO = {};
for (const f of features) {
  const id = String(f.properties.id);
  const d = svgPath(f.geometry);
  if (!d) { console.warn(`warning: ${id} vanished during simplification`); continue; }
  const { lx, ly, a } = labelAndArea(f);
  const extra = Object.fromEntries(props.filter(p => f.properties[p] !== undefined).map(p => [p, f.properties[p]]));
  reg.push({ id, ...extra, d, lx, ly, a });
  const [lat, lng] = (() => { const [x, y] = proj.invert([lx, ly]); return [Math.round(y * 1e4) / 1e4, Math.round(x * 1e4) / 1e4]; })();
  GEO[id] = { rings: geoRings(f, proj), lab: [lat, lng] };
}
const ctx = o['no-context'] ? '' : await contextPath(proj, w, h, o.iso3);
const DATA = { w, h, kpu: kmPerUnit(proj, w, h), proj: def, reg, ctx, ...(o.base ? landAndLines(topo) : {}) };

fs.mkdirSync(o.out, { recursive: true });
const head = `// Generated by tools/geo2quiz.mjs from ${path.basename(o.in)} (${reg.length} areas, equal-area conic, ${w}x${h} map units)${o.note ? `\n// ${o.note}` : ''}\n`;
fs.writeFileSync(path.join(o.out, o['data-file']), `${head}const ${o['data-var']} = ${JSON.stringify(DATA)};\n`);
fs.writeFileSync(path.join(o.out, o['geo-file']), `// Street-map rings [lat, lng] for the areas in ${o['data-file']} (same simplification)\nconst ${o['geo-var']} = ${JSON.stringify(GEO)};\n`);
const kb = f => (fs.statSync(path.join(o.out, f)).size / 1024).toFixed(0) + ' KB';
console.log(`${reg.length} areas, map ${w}x${h}, ${o['data-file']} ${kb(o['data-file'])}, ${o['geo-file']} ${kb(o['geo-file'])}`);
