// Brazil states map, shared by three pages through <body data-kinds>:
//   brazil-cep     postcodes (CEP): first digit (10 postal regions) and the first two digits
//   brazil-states  states by name (kind 'states', saved under 'dddstates' as before) and by their two letters (UF)
//   brazil-roads   state road prefixes (SP-, LMG-, ERS-, …) on km markers and route shields
// Map areas: the 27 states from IBGE municipalities (HDX COD-AB, CC BY-IGO), São Paulo split by municipality into
// CEP region 0 (the 39 municipalities of Greater São Paulo, CEPs 01000-09999) and region 1 (the rest, 11000-19999).
// CEP ranges: Correios (via pt.wikipedia "Código de Endereçamento Postal" and "Lista de municípios de São Paulo
// por CEP"). Road prefixes: DER-MG, DER-SP, DAER-RS, DER-PR and DER-PE nomenclature.

const LAYERS = {
  key: "brcep",
  size: [1000,919],
  pad: 18,
  maxZoom: 20,
  labelScale: 0.42,
  fly: {"pad":3,"min":0.15},
  street: {"bounds":[[-33.8,-74],[5.3,-34.8]],"maxBounds":[[-42,-85],[14,-25]]},
  hintLabel: "Color by CEP first digit",
  exploreKind: "states",
  kinds: [
    {
      key: "states",
      label: "States",
      noun: ["state","states"],
      prompt: "name",
      lang: "Names",
      groups: [["North","",["AC","AP","AM","PA","RO","RR","TO"]],["Northeast","",["AL","BA","CE","MA","PB","PE","PI","RN","SE"]],["Central-West","",["DF","GO","MT","MS"]],["Southeast","",["ES","MG","RJ","SP"]],["South","",["PR","RS","SC"]]],
      areas: {"x":{"AC":["AC"],"AP":["AP"],"AM":["AM"],"PA":["PA"],"RO":["RO"],"RR":["RR"],"TO":["TO"],"AL":["AL"],"BA":["BA"],"CE":["CE"],"MA":["MA"],"PB":["PB"],"PE":["PE"],"PI":["PI"],"RN":["RN"],"SE":["SE"],"DF":["DF"],"GO":["GO"],"MT":["MT"],"MS":["MS"],"ES":["ES"],"MG":["MG"],"RJ":["RJ"],"SP":["SP0","SP1"],"PR":["PR"],"RS":["RS"],"SC":["SC"]}},
      name: {"x":{"AC":"Acre","AP":"Amapá","AM":"Amazonas","PA":"Pará","RO":"Rondônia","RR":"Roraima","TO":"Tocantins","AL":"Alagoas","BA":"Bahia","CE":"Ceará","MA":"Maranhão","PB":"Paraíba","PE":"Pernambuco","PI":"Piauí","RN":"Rio Grande do Norte","SE":"Sergipe","DF":"Distrito Federal","GO":"Goiás","MT":"Mato Grosso","MS":"Mato Grosso do Sul","ES":"Espírito Santo","MG":"Minas Gerais","RJ":"Rio de Janeiro","SP":"São Paulo","PR":"Paraná","RS":"Rio Grande do Sul","SC":"Santa Catarina"}},
      short: "{id}",
      chip: "{name}",
      chipTitle: "{id}",
      about: "{id}",
      clicked: "{name}",
    },
    {
      key: "letters",
      label: "Letters",
      noun: ["state","states"],
      prompt: "name",
      hintLabel: "Color each state",
      of: "states",
      lang: "Letters",
      groups: [["North","",["AC","AM","AP","PA","RO","RR","TO"]],["Northeast","",["AL","BA","CE","MA","PB","PE","PI","RN","SE"]],["Central-West","",["DF","GO","MS","MT"]],["Southeast","",["ES","MG","RJ","SP"]],["South","",["PR","RS","SC"]]],
      areas: {"x":{"AC":["AC"],"AM":["AM"],"AP":["AP"],"PA":["PA"],"RO":["RO"],"RR":["RR"],"TO":["TO"],"AL":["AL"],"BA":["BA"],"CE":["CE"],"MA":["MA"],"PB":["PB"],"PE":["PE"],"PI":["PI"],"RN":["RN"],"SE":["SE"],"DF":["DF"],"GO":["GO"],"MS":["MS"],"MT":["MT"],"ES":["ES"],"MG":["MG"],"RJ":["RJ"],"SP":["SP0","SP1"],"PR":["PR"],"RS":["RS"],"SC":["SC"]}},
      name: "{id}",
      short: "{id}",
      chip: "{id}",
      chipTitle: {"x":{"AC":"Acre","AM":"Amazonas","AP":"Amapá","PA":"Pará","RO":"Rondônia","RR":"Roraima","TO":"Tocantins","AL":"Alagoas","BA":"Bahia","CE":"Ceará","MA":"Maranhão","PB":"Paraíba","PE":"Pernambuco","PI":"Piauí","RN":"Rio Grande do Norte","SE":"Sergipe","DF":"Distrito Federal","GO":"Goiás","MS":"Mato Grosso do Sul","MT":"Mato Grosso","ES":"Espírito Santo","MG":"Minas Gerais","RJ":"Rio de Janeiro","SP":"São Paulo","PR":"Paraná","RS":"Rio Grande do Sul","SC":"Santa Catarina"}},
      about: "{chipTitle}",
      clicked: "{p} · {chipTitle}",
    },
    {
      key: "roads",
      label: "Road prefixes",
      noun: ["prefix","prefixes"],
      prompt: "dial",
      hintLabel: "Color each state",
      groups: [["North","",["AC","AP","AM","PA","RO","RR","TO"]],["Northeast","",["AL","BA","CE","MA","PB","PE","VPE","PI","RN","SE"]],["Central-West","",["DF","GO","MT","MS"]],["Southeast","",["ES","MG","MGC","LMG","AMG","RJ","SP","SPA","SPI","SPM"]],["South","",["PR","PRC","ERS","RSC","VRS","SC"]]],
      areas: {"x":{"AC":["AC"],"AP":["AP"],"AM":["AM"],"PA":["PA"],"RO":["RO"],"RR":["RR"],"TO":["TO"],"AL":["AL"],"BA":["BA"],"CE":["CE"],"MA":["MA"],"PB":["PB"],"PE":["PE"],"VPE":["PE"],"PI":["PI"],"RN":["RN"],"SE":["SE"],"DF":["DF"],"GO":["GO"],"MT":["MT"],"MS":["MS"],"ES":["ES"],"MG":["MG"],"MGC":["MG"],"LMG":["MG"],"AMG":["MG"],"RJ":["RJ"],"SP":["SP0","SP1"],"SPA":["SP0","SP1"],"SPI":["SP0","SP1"],"SPM":["SP0","SP1"],"PR":["PR"],"PRC":["PR"],"ERS":["RS"],"RSC":["RS"],"VRS":["RS"],"SC":["SC"]}},
      name: "{id}",
      short: "{id}",
      chip: "{id}",
      chipTitle: {"x":{"AC":"Acre · state roads","AP":"Amapá · state roads","AM":"Amazonas · state roads","PA":"Pará · state roads","RO":"Rondônia · state roads","RR":"Roraima · state roads","TO":"Tocantins · state roads","AL":"Alagoas · state roads","BA":"Bahia · state roads","CE":"Ceará · state roads","MA":"Maranhão · state roads","PB":"Paraíba · state roads","PE":"Pernambuco · state roads","VPE":"Pernambuco · vicinal","PI":"Piauí · state roads","RN":"Rio Grande do Norte · state roads","SE":"Sergipe · state roads","DF":"Distrito Federal · state roads","GO":"Goiás · state roads","MT":"Mato Grosso · state roads","MS":"Mato Grosso do Sul · state roads","ES":"Espírito Santo · state roads","MG":"Minas Gerais · state roads","MGC":"Minas Gerais · coincident","LMG":"Minas Gerais · link","AMG":"Minas Gerais · access","RJ":"Rio de Janeiro · state roads","SP":"São Paulo · state roads","SPA":"São Paulo · access","SPI":"São Paulo · interconnection","SPM":"São Paulo · frontage","PR":"Paraná · state roads","PRC":"Paraná · coincident","ERS":"Rio Grande do Sul · state roads","RSC":"Rio Grande do Sul · coincident","VRS":"Rio Grande do Sul · vicinal","SC":"Santa Catarina · state roads"}},
      about: {"x":{"AC":["Acre","state roads"],"AP":["Amapá","state roads"],"AM":["Amazonas","state roads"],"PA":["Pará","state roads"],"RO":["Rondônia","state roads"],"RR":["Roraima","state roads"],"TO":["Tocantins","state roads"],"AL":["Alagoas","state roads"],"BA":["Bahia","state roads"],"CE":["Ceará","state roads"],"MA":["Maranhão","state roads"],"PB":["Paraíba","state roads"],"PE":["Pernambuco","state roads"],"VPE":["Pernambuco","vicinal"],"PI":["Piauí","state roads"],"RN":["Rio Grande do Norte","state roads"],"SE":["Sergipe","state roads"],"DF":["Distrito Federal","state roads"],"GO":["Goiás","state roads"],"MT":["Mato Grosso","state roads"],"MS":["Mato Grosso do Sul","state roads"],"ES":["Espírito Santo","state roads"],"MG":["Minas Gerais","state roads"],"MGC":["Minas Gerais","coincident"],"LMG":["Minas Gerais","link"],"AMG":["Minas Gerais","access"],"RJ":["Rio de Janeiro","state roads"],"SP":["São Paulo","state roads"],"SPA":["São Paulo","access"],"SPI":["São Paulo","interconnection"],"SPM":["São Paulo","frontage"],"PR":["Paraná","state roads"],"PRC":["Paraná","coincident"],"ERS":["Rio Grande do Sul","state roads"],"RSC":["Rio Grande do Sul","coincident"],"VRS":["Rio Grande do Sul","vicinal"],"SC":["Santa Catarina","state roads"]}},
      dial: {"x":{"AC":[["AC","hot"],["-···","cold"]],"AP":[["AP","hot"],["-···","cold"]],"AM":[["AM","hot"],["-···","cold"]],"PA":[["PA","hot"],["-···","cold"]],"RO":[["RO","hot"],["-···","cold"]],"RR":[["RR","hot"],["-···","cold"]],"TO":[["TO","hot"],["-···","cold"]],"AL":[["AL","hot"],["-···","cold"]],"BA":[["BA","hot"],["-···","cold"]],"CE":[["CE","hot"],["-···","cold"]],"MA":[["MA","hot"],["-···","cold"]],"PB":[["PB","hot"],["-···","cold"]],"PE":[["PE","hot"],["-···","cold"]],"VPE":[["VPE","hot"],["-···","cold"]],"PI":[["PI","hot"],["-···","cold"]],"RN":[["RN","hot"],["-···","cold"]],"SE":[["SE","hot"],["-···","cold"]],"DF":[["DF","hot"],["-···","cold"]],"GO":[["GO","hot"],["-···","cold"]],"MT":[["MT","hot"],["-···","cold"]],"MS":[["MS","hot"],["-···","cold"]],"ES":[["ES","hot"],["-···","cold"]],"MG":[["MG","hot"],["-···","cold"]],"MGC":[["MGC","hot"],["-···","cold"]],"LMG":[["LMG","hot"],["-···","cold"]],"AMG":[["AMG","hot"],["-····","cold"]],"RJ":[["RJ","hot"],["-···","cold"]],"SP":[["SP","hot"],["-···","cold"]],"SPA":[["SPA","hot"],[" ···/···","cold"]],"SPI":[["SPI","hot"],[" ···/···","cold"]],"SPM":[["SPM","hot"],[" ··· D","cold"]],"PR":[["PR","hot"],["-···","cold"]],"PRC":[["PRC","hot"],["-···","cold"]],"ERS":[["ERS","hot"],["-···","cold"]],"RSC":[["RSC","hot"],["-···","cold"]],"VRS":[["VRS","hot"],["-···","cold"]],"SC":[["SC","hot"],["-···","cold"]]}},
      clicked: {"t":"{p} ({about0})","x":{"PE":"PE · VPE (Pernambuco)","MG":"MG · MGC · LMG · AMG (Minas Gerais)","SP1":"SP · SPA · SPI · SPM (São Paulo)","SP0":"SP · SPA · SPI · SPM (São Paulo)","PR":"PR · PRC (Paraná)","RS":"ERS · RSC · VRS (Rio Grande do Sul)"}},
    },
    {
      key: "zone",
      label: "First digit",
      noun: ["region","regions"],
      prompt: "dial",
      hints: false,
      groups: [["CEP regions","",["0","1","2","3","4","5","6","7","8","9"]]],
      areas: "@zone",
      name: "CEP {@zone}",
      short: "{id}",
      chip: "{id}",
      chipTitle: {"x":{"0":"Greater São Paulo","1":"São Paulo, rest of state","2":"Espírito Santo, Rio de Janeiro","3":"Minas Gerais","4":"Sergipe, Bahia","5":"Rio Grande do Norte, Paraíba, Pernambuco, Alagoas","6":"Acre, Amazonas, Roraima, Pará, Amapá, Maranhão, Piauí, Ceará","7":"Rondônia, Tocantins, Mato Grosso do Sul, Mato Grosso, Goiás, Distrito Federal","8":"Paraná, Santa Catarina","9":"Rio Grande do Sul"}},
      about: "{chipTitle}",
      dial: {"t":[["{id}","hot"],["····-···","cold"]]},
      clicked: {"x":{"RO":"7 · Rondônia","AC":"6 · Acre","AM":"6 · Amazonas","RR":"6 · Roraima","PA":"6 · Pará","AP":"6 · Amapá","TO":"7 · Tocantins","MA":"6 · Maranhão","PI":"6 · Piauí","CE":"6 · Ceará","RN":"5 · Rio Grande do Norte","PB":"5 · Paraíba","PE":"5 · Pernambuco","AL":"5 · Alagoas","SE":"4 · Sergipe","BA":"4 · Bahia","MG":"3 · Minas Gerais","ES":"2 · Espírito Santo","RJ":"2 · Rio de Janeiro","SP1":"1 · São Paulo, rest of state","SP0":"0 · Greater São Paulo","PR":"8 · Paraná","SC":"8 · Santa Catarina","RS":"9 · Rio Grande do Sul","MS":"7 · Mato Grosso do Sul","MT":"7 · Mato Grosso","GO":"7 · Goiás","DF":"7 · Distrito Federal"}},
    },
    {
      key: "two",
      label: "Two digits",
      noun: ["prefix","prefixes"],
      prompt: "dial",
      groups: [["0x","SP",["01","02","03","04","05","06","07","08","09"]],["1x","SP",["11","12","13","14","15","16","17","18","19"]],["2x","ES, RJ",["20","21","22","23","24","25","26","27","28","29"]],["3x","MG",["30","31","32","33","34","35","36","37","38","39"]],["4x","SE, BA",["40","41","42","43","44","45","46","47","48","49"]],["5x","RN, PB, PE, AL",["50","51","52","53","54","55","56","57","58","59"]],["6x","AC, AM, RR, PA, AP, MA, PI, CE",["60","61","62","63","64","65","66","67","68","69"]],["7x","RO, TO, MS, MT, GO, DF",["70","71","72","73","74","75","76","77","78","79"]],["8x","PR, SC",["80","81","82","83","84","85","86","87","88","89"]],["9x","RS",["90","91","92","93","94","95","96","97","98","99"]]],
      areas: {"x":{"11":["SP1"],"12":["SP1"],"13":["SP1"],"14":["SP1"],"15":["SP1"],"16":["SP1"],"17":["SP1"],"18":["SP1"],"19":["SP1"],"20":["RJ"],"21":["RJ"],"22":["RJ"],"23":["RJ"],"24":["RJ"],"25":["RJ"],"26":["RJ"],"27":["RJ"],"28":["RJ"],"29":["ES"],"30":["MG"],"31":["MG"],"32":["MG"],"33":["MG"],"34":["MG"],"35":["MG"],"36":["MG"],"37":["MG"],"38":["MG"],"39":["MG"],"40":["BA"],"41":["BA"],"42":["BA"],"43":["BA"],"44":["BA"],"45":["BA"],"46":["BA"],"47":["BA"],"48":["BA"],"49":["SE"],"50":["PE"],"51":["PE"],"52":["PE"],"53":["PE"],"54":["PE"],"55":["PE"],"56":["PE"],"57":["AL"],"58":["PB"],"59":["RN"],"60":["CE"],"61":["CE"],"62":["CE"],"63":["CE"],"64":["PI"],"65":["MA"],"66":["PA"],"67":["PA"],"68":["PA","AP"],"69":["AM","RR","AC"],"70":["DF"],"71":["DF"],"72":["DF","GO"],"73":["DF","GO"],"74":["GO"],"75":["GO"],"76":["GO","RO"],"77":["TO"],"78":["MT"],"79":["MS"],"80":["PR"],"81":["PR"],"82":["PR"],"83":["PR"],"84":["PR"],"85":["PR"],"86":["PR"],"87":["PR"],"88":["SC"],"89":["SC"],"90":["RS"],"91":["RS"],"92":["RS"],"93":["RS"],"94":["RS"],"95":["RS"],"96":["RS"],"97":["RS"],"98":["RS"],"99":["RS"],"01":["SP0"],"02":["SP0"],"03":["SP0"],"04":["SP0"],"05":["SP0"],"06":["SP0"],"07":["SP0"],"08":["SP0"],"09":["SP0"]}},
      name: "CEP {id}",
      short: "{id}",
      chip: "{id}",
      chipTitle: {"x":{"11":"São Paulo, rest of state","12":"São Paulo, rest of state","13":"São Paulo, rest of state","14":"São Paulo, rest of state","15":"São Paulo, rest of state","16":"São Paulo, rest of state","17":"São Paulo, rest of state","18":"São Paulo, rest of state","19":"São Paulo, rest of state","20":"Rio de Janeiro","21":"Rio de Janeiro","22":"Rio de Janeiro","23":"Rio de Janeiro","24":"Rio de Janeiro","25":"Rio de Janeiro","26":"Rio de Janeiro","27":"Rio de Janeiro","28":"Rio de Janeiro","29":"Espírito Santo","30":"Minas Gerais","31":"Minas Gerais","32":"Minas Gerais","33":"Minas Gerais","34":"Minas Gerais","35":"Minas Gerais","36":"Minas Gerais","37":"Minas Gerais","38":"Minas Gerais","39":"Minas Gerais","40":"Bahia","41":"Bahia","42":"Bahia","43":"Bahia","44":"Bahia","45":"Bahia","46":"Bahia","47":"Bahia","48":"Bahia","49":"Sergipe","50":"Pernambuco","51":"Pernambuco","52":"Pernambuco","53":"Pernambuco","54":"Pernambuco","55":"Pernambuco","56":"Pernambuco","57":"Alagoas","58":"Paraíba","59":"Rio Grande do Norte","60":"Ceará","61":"Ceará","62":"Ceará","63":"Ceará","64":"Piauí","65":"Maranhão","66":"Pará","67":"Pará","68":"Pará, Amapá","69":"Amazonas, Roraima, Acre","70":"Distrito Federal","71":"Distrito Federal","72":"Distrito Federal, Goiás","73":"Distrito Federal, Goiás","74":"Goiás","75":"Goiás","76":"Goiás, Rondônia","77":"Tocantins","78":"Mato Grosso","79":"Mato Grosso do Sul","80":"Paraná","81":"Paraná","82":"Paraná","83":"Paraná","84":"Paraná","85":"Paraná","86":"Paraná","87":"Paraná","88":"Santa Catarina","89":"Santa Catarina","90":"Rio Grande do Sul","91":"Rio Grande do Sul","92":"Rio Grande do Sul","93":"Rio Grande do Sul","94":"Rio Grande do Sul","95":"Rio Grande do Sul","96":"Rio Grande do Sul","97":"Rio Grande do Sul","98":"Rio Grande do Sul","99":"Rio Grande do Sul","01":"Greater São Paulo","02":"Greater São Paulo","03":"Greater São Paulo","04":"Greater São Paulo","05":"Greater São Paulo","06":"Greater São Paulo","07":"Greater São Paulo","08":"Greater São Paulo","09":"Greater São Paulo"}},
      detail: ["Show state",{"t":"{@uf}","x":{"68":"PA, AP","69":"AM, RR, AC","72":"DF, GO","73":"DF, GO","76":"GO, RO"}}],
      about: "{chipTitle}",
      dial: {"t":[["{id}","hot"],["···-···","cold"]]},
      clicked: {"x":{"RO":"76 · Rondônia","AC":"69 · Acre","AM":"69 · Amazonas","RR":"69 · Roraima","PA":"66–68 · Pará","AP":"68 · Amapá","TO":"77 · Tocantins","MA":"65 · Maranhão","PI":"64 · Piauí","CE":"60–63 · Ceará","RN":"59 · Rio Grande do Norte","PB":"58 · Paraíba","PE":"50–56 · Pernambuco","AL":"57 · Alagoas","SE":"49 · Sergipe","BA":"40–48 · Bahia","MG":"30–39 · Minas Gerais","ES":"29 · Espírito Santo","RJ":"20–28 · Rio de Janeiro","SP1":"11–19 · São Paulo, rest of state","SP0":"01–09 · Greater São Paulo","PR":"80–87 · Paraná","SC":"88–89 · Santa Catarina","RS":"90–99 · Rio Grande do Sul","MS":"79 · Mato Grosso do Sul","MT":"78 · Mato Grosso","GO":"72–76 · Goiás","DF":"70–73 · Distrito Federal"}},
      areaLabel: {"t":"{p}","x":{"PA":"66–68","CE":"60–63","PE":"50–56","BA":"40–48","MG":"30–39","RJ":"20–28","SP1":"11–19","SP0":"01–09","PR":"80–87","SC":"88–89","RS":"90–99","GO":"72–76","DF":"70–73"}},
    },
  ],
  g: "{@zone}",
  explore: {"t":{"code":"{@uf}","title":"{states.name}","sub":["{two.name}","{a}"]},"x":{"PA":{"code":"PA","title":"Pará","sub":["CEP 66–68","PA"]},"CE":{"code":"CE","title":"Ceará","sub":["CEP 60–63","CE"]},"PE":{"code":"PE","title":"Pernambuco","sub":["CEP 50–56","PE · VPE"]},"BA":{"code":"BA","title":"Bahia","sub":["CEP 40–48","BA"]},"MG":{"code":"MG","title":"Minas Gerais","sub":["CEP 30–39","MG · MGC · LMG · AMG"]},"RJ":{"code":"RJ","title":"Rio de Janeiro","sub":["CEP 20–28","RJ"]},"SP1":{"code":"SP","title":"São Paulo","sub":["São Paulo, rest of state · CEP 11–19","SP · SPA · SPI · SPM"]},"SP0":{"code":"SP","title":"São Paulo","sub":["Greater São Paulo · CEP 01–09","SP · SPA · SPI · SPM"]},"PR":{"code":"PR","title":"Paraná","sub":["CEP 80–87","PR · PRC"]},"SC":{"code":"SC","title":"Santa Catarina","sub":["CEP 88–89","SC"]},"RS":{"code":"RS","title":"Rio Grande do Sul","sub":["CEP 90–99","ERS · RSC · VRS"]},"GO":{"code":"GO","title":"Goiás","sub":["CEP 72–76","GO"]},"DF":{"code":"DF","title":"Distrito Federal","sub":["CEP 70–73","DF"]}}},
};
