#!/usr/bin/env node
// The map of the US states quiz: the 3,143 counties and county equivalents of the 50 states and Washington, D.C.,
// from the Census Bureau's cartographic boundary file of 2021 (cb_2021_us_county_5m, public domain). 2021 is the
// last year with Connecticut's eight counties (from 2022 the Bureau lists its nine planning regions instead) and it
// has Alaska's areas as they are since 2019 (Chugach and Copper River in place of Valdez-Cordova).
// Drawn in the map space of the US city quiz (Albers USA, Alaska and Hawaii as insets), with its neighbouring land.
//
//   node tools/builds/us-counties/build.mjs      writes quizzes/us-states/data.js, geo.js, style.css and layers.js
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { execFileSync } from 'node:child_process';
import * as d3 from 'd3-geo';
import { neighbors, mesh } from 'topojson-client';
import { cached, rewind, planarFeatures, labelAndArea, geoRings, kmPerUnit, svgPath, ROOT } from '../../lib/geo.mjs';

const zip = await cached('https://www2.census.gov/geo/tiger/GENZ2021/kml/cb_2021_us_county_5m.zip', 'builds/us-counties/cb_2021_county_5m_kml.zip');
const kml = execFileSync('unzip', ['-p', zip, '*.kml'], { maxBuffer: 1 << 28 }).toString('utf8');
const features = [];
for (const pm of kml.split('<Placemark').slice(1)) {
  const p = Object.fromEntries([...pm.matchAll(/<SimpleData name="(\w+)">([^<]*)<\/SimpleData>/g)].map(m => [m[1], m[2].replace(/&amp;/g, '&').replace(/&apos;/g, "'")]));
  if (+p.STATEFP > 56) continue; // the territories are not in the quiz
  const ring = s => s.trim().split(/\s+/).map(c => c.split(',').slice(0, 2).map(Number));
  const polys = [...pm.matchAll(/<Polygon>([\s\S]*?)<\/Polygon>/g)].map(m => [ring(/<outerBoundaryIs>[\s\S]*?<coordinates>([\s\S]*?)<\/coordinates>/.exec(m[1])[1]), ...[...m[1].matchAll(/<innerBoundaryIs>[\s\S]*?<coordinates>([\s\S]*?)<\/coordinates>/g)].map(i => ring(i[1]))]);
  features.push({ type: 'Feature', properties: { id: p.GEOID, name: p.NAME, full: p.NAMELSAD, st: p.STATE_NAME, ab: p.STUSPS }, geometry: { type: 'MultiPolygon', coordinates: polys } });
}
const fc = rewind({ type: 'FeatureCollection', features });

const CITIES = vm.runInNewContext(fs.readFileSync(path.join(ROOT, 'quizzes/us-cities/cities.js'), 'utf8') + ';CITIES');
const def = CITIES.proj, proj = d3.geoAlbersUsa().scale(def.scale).translate(def.translate);
const { topo, features: drawn } = planarFeatures(fc, proj, { minArea: 0.05, dropRing: 0.05 });
const reg = [], GEO = {};
for (const f of drawn) {
  const d = svgPath(f.geometry);
  if (!d) { console.warn('vanished:', f.properties.full, f.properties.ab); continue; }
  const { lx, ly, a } = labelAndArea(f), { id, name, full, st, ab } = f.properties, ll = proj.invert([lx, ly]);
  reg.push({ id, name, full, st, ab, d, lx, ly, a });
  GEO[id] = { rings: geoRings(f, proj), lab: [Math.round(ll[1] * 1e4) / 1e4, Math.round(ll[0] * 1e4) / 1e4] };
}
reg.sort((a, b) => a.id.localeCompare(b.id));
// the lines between states, drawn thicker on top of the county lines
const lines = mesh(topo, topo.objects.a, (a, b) => a !== b && a.properties.st !== b.properties.st).coordinates;
const ent = [lines.map(l => 'M' + l.map(([x, y]) => `${Math.round(x * 10) / 10},${Math.round(y * 10) / 10}`).join('L')).join('')];
const DATA = { w: CITIES.w, h: CITIES.h, kpu: CITIES.kpu ?? kmPerUnit(proj, CITIES.w, CITIES.h), proj: def, reg, ent, ctx: CITIES.ctx };

// hint colors by state: no two states that touch share one
const geoms = topo.objects.a.geometries, near = neighbors(geoms), touch = {};
geoms.forEach((g, i) => { const s = g.properties.st; touch[s] ??= new Set(); for (const j of near[i]) if (geoms[j].properties.st !== s) touch[s].add(geoms[j].properties.st); });
const color = {}, used = Array(24).fill(0);
for (const s of Object.keys(touch).sort((a, b) => touch[b].size - touch[a].size || a.localeCompare(b))) {
  const taken = new Set([...touch[s]].map(n => color[n]).filter(Boolean));
  let best = 0; for (let h = 1; h <= 24; h++) if (!taken.has(h) && (!best || used[h - 1] < used[best - 1])) best = h;
  color[s] = best; used[best - 1]++;
}
const out = f => path.join(ROOT, 'quizzes/us-states', f);
fs.writeFileSync(out('data.js'), `// Generated by tools/builds/us-counties/build.mjs: ${reg.length} counties and county equivalents (US Census Bureau, cartographic\n// boundary file 2021, public domain), in the map space of ../us-cities (${DATA.w}x${DATA.h} map units, Albers USA: Alaska and Hawaii are insets)\nconst DATA = ${JSON.stringify(DATA)};\n`);
fs.writeFileSync(out('geo.js'), `// Street-map rings [lat, lng] for the areas in data.js (same simplification)\nconst GEO = ${JSON.stringify(GEO)};\n`);
fs.writeFileSync(out('style.css'), `/* hint colors by state (tools/builds/us-counties/build.mjs) */\n${Object.keys(color).sort().map(s => `.r[data-g="${s}"]{--hint:var(--h${color[s]})}`).join(' ')}\n`);
// The quiz's data: the states (groups of their counties, in the Census Bureau's four regions) and the counties.
const REGIONS = { Northeast: 'CT ME MA NH NJ NY PA RI VT', Midwest: 'IL IN IA KS MI MN MO NE ND OH SD WI', South: 'AL AR DE DC FL GA KY LA MD MS NC OK SC TN TX VA WV', West: 'AK AZ CA CO HI ID MT NV NM OR UT WA WY' };
const stateOf = Object.fromEntries(reg.map(r => [r.ab, r.st])), count = reg.reduce((m, r) => (m[r.st] = (m[r.st] || 0) + 1, m), {});
const unit = s => s === 'Louisiana' ? 'parishes' : s === 'Alaska' ? 'boroughs and census areas' : 'counties';
const LAYERS = {
  key: 'usstates', borders: 'DATA.ent', size: [DATA.w, DATA.h], pad: 16, maxZoom: 60, labelScale: 0.14, fly: { pad: 1.6, min: 0.03 },
  street: { bounds: [[24.4, -124.8], [49.4, -66.9]], maxBounds: [[10, -200], [75, -50]] },
  hintLabel: 'Color by state', exploreKind: 'counties',
  kinds: [
    { key: 'states', label: 'States', noun: ['state', 'states'], prompt: 'name',
      groups: Object.entries(REGIONS).map(([region, list]) => [region, '', list.split(' ').map(ab => stateOf[ab]).sort()]),
      areas: '@st', name: '{id}', short: '{@ab}', chip: '{id}', chipTitle: '{@ab}',
      about: { x: Object.fromEntries(Object.keys(count).map(s => [s, s === 'District of Columbia' ? 'Federal district' : `${count[s]} ${unit(s)}`])) }, clicked: '{p}' },
    { key: 'counties', label: 'Counties', noun: ['county', 'counties'], prompt: 'name',
      groups: Object.keys(count).sort().map(s => [s, '', reg.filter(r => r.st === s).sort((a, b) => a.full.localeCompare(b.full)).map(r => r.id)]),
      areas: '@id', name: '{@full}, {@ab}', short: '{@name}', chip: '{@full}', chipTitle: '{@st}', about: ['{@st}'], clicked: '{name}' },
  ],
  g: '{@st}',
  explore: { code: '{@ab}', title: '{@full}', sub: ['{@st}'] },
};
const ident = k => /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
const lit = L => '{\n' + Object.entries(L).map(([k, v]) => k === 'kinds' ? '  kinds: [\n' + v.map(kind => '    {\n' + Object.entries(kind).map(([p, x]) => `      ${ident(p)}: ${JSON.stringify(x)},`).join('\n') + '\n    },').join('\n') + '\n  ],' : `  ${ident(k)}: ${JSON.stringify(v)},`).join('\n') + '\n}';
fs.writeFileSync(out('layers.js'), `// US states and counties, on the county map (data.js). A state is the group of its counties; Washington, D.C. is one of\n// the 51. The four regions are the Census Bureau's. Written by tools/builds/us-counties/build.mjs.\n\nconst LAYERS = ${lit(LAYERS)};\n`);
const kb = f => (fs.statSync(out(f)).size / 1024).toFixed(0) + ' KB';
console.log(`${reg.length} counties in ${Object.keys(color).length} states; data.js ${kb('data.js')}, geo.js ${kb('geo.js')}`);
console.log('per state:', Object.entries(reg.reduce((m, r) => (m[r.ab] = (m[r.ab] || 0) + 1, m), {})).sort((a, b) => b[1] - a[1]).map(([s, n]) => s + ' ' + n).join(', '));
